---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: apps
spec:
  encryptedData:
    token: AgB4VDVtK3fyNnVU/iDiRRH5nyHWcaLAxxevfMXNJYVQtphAi3d4N9HGr81QyASJcb6Ge7WFXJoo+odrJO8J08z6tLy4jSjBGVdWa3h03plMrxyfNsc4HZohACohy0feNxxBDavug2XbEotSJYO9g05dtEgXH5vJ2yH0A/htu3b3OYC3gJIUsTgMzgHMvgFCKlpte6ujj2vSkoGFG0E4l7hDpnlBzjK3uyQlUHXhVnquP6uf0JovuT/aHJDrI0ZTkBgDtJY1Qa3WppzgpCVrSBQlKdAc3+wfkQ4Igiim1oG7My/Cczh7gtjYVr3QvWYeghU1bZcD+hgWPheERexBSNYWegBXNIUT+niOL+GUDBw0P9WLarRK6QwkDRE16vYgCg1wrcIUrIfvIGYZQLPExblixCE2tnR2tfpfhkC8yDc8vXqH09fFl+Cr3v7q55RGyUqXSWGQQp+ziR80eZuxv5Ckl92lrGpe4VV/mzUdr6AJHM8pjXQLtQhJsqIgGrzf7+DEdZDJe2nE7ShSi0H1G3WW0Yz44cf2B/1IPFK2jhSqXMAPK05vP+D3nT/etwpzJgmbKW7ZFzAfWSWfZeoKEDjaIzJ8leSXa/7jy/u3iw2IBFopa/3fuTTcFxh1QatIMCY36mGlB8jL+edHAjEU2N5Hy5iLYIOmXjlfRoYbqW5cN1lNI4SiS0ukJEiNSs21x0Q0tO0FyNezebaGHuqguaoT3q64v5ekf2mkPFiM6hEYA9i/T172gkEG
  template:
    metadata:
      name: renovate-github-token
      namespace: apps
    type: Opaque
