---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: apps
spec:
  encryptedData:
    token: AgDBiMLts88fNrC0IxFSanAV+QMZ45I3fwvOyxKMyIPlXSNFTO7bo/TzZEXffdJOEva0M2kG0x/GmigiHZ1ro1r5AS8zuJxiU1KpoULtYjXLj/n5KMTIHKWUkrZwdBZx8mUmD1dn0Ba2MWUFXG3Uglcr27HczC2b19sq6A8zz9SoAywUefTTWKFV6udcZBD80Gf2XoK8qa+K1VLBQ5d2wXjrKSQAQuFl+In3T1jrSFEhY9Frz9FrdiJb4FHif2aIHo7ojBoQjrGi8/yXap60C4EqWJkNjns8K42pEUliwT4QAaZmnHYAebxdqGGMlZuS8cflHU/3ANWn+J2/cXX3SFOdD44h3WOM9pWq1KPOil/V7oPdso6qnRwTmWc7OE+a0DQQdELEUmHWkc7sysT9nYBGd3TMhdkaj9gMFJ2sbfFOX5KWZfsDILa9B5uh5kZ0gEqh3VnudDQmY5yUh6PF6PQcrDWZqgKOo72n0j4oQad4djOInU2aHGDO4MKBhWk/mGJHepBDLpbKmdaNIgVHCzBFqGwyVpcy5m0rw/mFS8iZH/7VoZTY92XOHnswUQHCHdRLMLOOIlz4D6XtukH0RTgZc2M1waxVigEVbj8+KdyN//ubI1PEI6LQ3spTSmMq1ul67KR8b3BPsnVMNz8jYER3580cI1lNu2bKeb1Fae3fXeifuVOWIlDohqjUkoBAsjwNg15f4DpCjf0jpCnYEUa0iIec4deUo/2Qnj7FjgzJbi//3izZkACA
  template:
    metadata:
      name: renovate-github-token
      namespace: apps
    type: Opaque
