---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-valkey
  namespace: apps
spec:
  encryptedData:
    REDIS_PASSWORD: AgCbg0FKvY6eZsjicpCSEeUTmHxPOF+f2nuDZDbBkawKP/fDtfqI/RgQqLnOtxZZW1vvTge4YwfbBLkLHQ1WHhg4dW22JA5222/n1isef6mZuVENy+aq8jIBQEUE9mid7gS10kMVXePJzgIwRuGv/qJu4uU2I2uOW3mI2INGINTofP3Ul7xpXP3oIVuBJgOk2os54TBxbI2L4YH2g/GROr47+r/O3TiDKqKS4N/oX4ihhJkVu3+b/8YKY6CFiCQEfUCx4fQaOJ4FOIbVZt9oJ2PC99y8Txc3M8clBK8b/UJv3+e2/gTdGap7OwnBK85Jq5PfWynbqkfd1xyRsphKtG9KGpLktyBe+D7HqchW+u+nwTd7vUQW6JHkVxEIryrxcgX46eNBMCiJ2ksZbB/ylMT7KEOdgb7K++1C9jNy9MjmEtmdq/sUhbdXCjmcNeEiwvRsaJ5HNjiEHqjAbB8i8pUTMlYoI7Yh0M14NT28bKWFYpydvd0LmJqDI/5oJYKWu2iF7PJxasNoroKwYePy3hIDkVSvn5ZpWMG+R3C0EW1tHBeIzZbghADXe/JRj1KWDmj2UdrUQwGwip5MsTHHsf4bav5cgjnXJOxHAOGLI/3Gn0/HSmLNKGLv0ONNZZqjyXyO2IQTKHFeOjTk1BqNBiq1Z3+toT7lMHE69hbcMvcSESFjHXT4y5ljl/aRD7TllzXO0sFssgzR7620u00LP6dx+Q0aH15H2cruOybzfEZDFQ==
    REDIS_USERNAME: AgB42+i3uIeuqYAEhyAo3/+6rdzGzryMu+v4A4Mwn0QoOAOxl0arkJTIkc+NmnOyFyfb/vTaqTZNXdPtP67HFVhiCacAhZG7ATqlXORVMfDaUqzj2uCoP8O8UW5XPYYBmg0zk4ZRN5OZDqEhwgP/GiM2aOZoC7mOuDl0VymhqNUTswHWK/CtRuEOTsSeI0FoRKbCsq1yx82EBe9FFJCjJq7Dp4cKl228WTKjeJeCIa2OnZEiH74JNA/5rUyLfmoO217JOqu5St5IY2DU1lU6ghWf50WX3ZwYxieBx8JIyxKu3dqePlEhy/L63A+jtZab0ICX3sdEhEMXgp9f8akfEdp7pa8JWioxpVJVp/BKlbglDrgYMwyqdhxl/Xa6IsMTe/O/uIfJ9/lML2yx2LcNmB/9fyPHMUm5xnvvLKlWXoySOMuodG+Mna3xc2ukTRBpF0QLoJWxrBGLB4YFgNzqUeRuxNtil3qoJSQzJf5Uxj0q3gW1mjNvDNYNr4SOWT/vKe1tRKYtJgsb3B6wue6eWAqcjgR3+Y5ORkFhjONLqb4SRtTJAiPJcu+XpjUlk54cbpXFq7my17QEhvvj+ZnH52HKitqqXMUTG1w0LlMxyptNNbDkRB3ln3xLDrcb//C+yDtUU/54jq7ZKa1VDSD/pGmrQc7qnkh93uLFCV95w0qM5W5edqIE4SgBHq6J/eQgJVACxVWZb6c=
  template:
    metadata:
      name: harbor-valkey
      namespace: apps
