---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-build-robot
  namespace: apps
spec:
  encryptedData:
    password: AgBnvJPJTSYQXo7hsgk8EFTnhujxBiU8OooWWgMfU38Q32Dzf3DyERoNdDCa//xRVR/JxkW6eHAux7VU6l6rZnNAYEPeJpXG+ruKvoDqaBy3xdjsctus+e1O0oAZ+mvt8tZCB8bdXUGOxP490iJ86uhSqt0dJ8NtDY7e7NYF3LiaEAlFjiHT03Gbaar5oEdnF9htb8JlTSM1goMNaGlxYhY0LAqEQDTwZksRt5wnD2QPrnYZDmPUo9/rqhfPkq6eh0NNvllaZMPXlBpOPaK2x9rFD32UJVDRdDuIFGj9sisPmnf2Ru9mdmQIeaNUuvY3dOzXS2QWTATU70Vwth/XD5jCzc4nulY2lQzP1Kv7usEPAjmYPBrYG5BiyFMSMPt3WDHjfPU561Hugh4l6lPBATRw86nLZDk+gdLeLTe3vfoi6Sn6G9wRHj/G0/dG//uwtXILetXeiriwnXhs2Ydy2KeRWQ7RHys1CW/jSV3tO2rbtpW2pT8pyXr0vg/9vu2xXR9mjrA+ZXE3stP/kl39vJnQUPZ939txPqYPdIkP8AR3Th6v5hQphMdDqU674rzjD8ExVEnrviI++PG9Q8fdww/XUBz5fboXjg5lJZYdzw5PGxowGoqTC+qtzsMtWX9BvDpZfI5OowHEFJdk1vqXZjT+aUilaSLod/ieJdeWGgZp/TtimXECsL+vVlcMa1fsv1AygMAjyVXXNneT302SoamvR7KOZPmWF6k12rYBweP4TQ==
    username: AgBgBcl8qxUDXfG/Jx/uP8t7WaKh6atzEcLoEOiHJBwcBcHn0R3ZQZovJhSNDQ0ZPcQSE8UK/axXYncug1F+xnEBEOqndxp8WHHWPzhhXc2aeTs5uyvDrwE29uuP7SDIQhVzec/EX/67IzjfHxbrNGqveglnuDNoF5EfkMWGbWAXbE5URoOxNLWmRIPxxJr38yeiKQsFhSN32bUENhcs043yS/V5od/Qcwtq6nNh9+9rCDlORkJAlwVo5lL4HYuk2vwlod6X8xHWG9vE9MGhI88ngFpmYPnWZfANMsin5DWpSE4mYPV3SFpCMJPj786YgRpoc3ThRiYg/R+U+1IB3Mz9dG9lf8KnhG6rQyJzUfz9gRjunXrhEl/jiZxPH8i9oyjdLTGHOS+80ZebmtRXaK1tjKKlcmQTDKl3/wSrgTyZULziSQntH7aIV8OFBOfHPnX/Edo9sRhfCIxqPfwLNRiGZPoY0aXW8FEZA8tDwnPdgfh1OL2vSeMMDZ5zMYkrsnkEIah4Wn7pyzYM2ptacVPdQJRqcWNWW+z8uxRxsQqp8hPcX5dJ4FmM7sAAUBvK2A+L7NnfrZJlZDjcrJbrHAmAnKzhu/ROr6TIPhVgeHYfIB3Nc05+IMR/5YdVdRM6lrYBwhkU7lZcIwnZ2miKFYYSMHk/jpzHKpZH5SNuvsHE36MpRJl7bfKt/EzN4nJA2dTEn4O6+l2O4S7qmonIovD/sfw=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: woodpecker
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: woodpecker
      name: harbor-build-robot
      namespace: apps
