---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-oidc
  namespace: apps
spec:
  encryptedData:
    client_id: AgCcayyJsf/9EAkxPXqOzGff1EUs9TYQFTvgthyYFrFpg7T2MrZCZ75daC0pmJasTz6mJz+Guj84cLfILf6wPer6CXDedqLjdlZr9qphVODdVxXXKPgPPydHMs9km3tTXs2OrlwUYdq3DYuwGRXAuyM/jXdzbYftGHCUbTDhajhWxDcNOq0aNV5HML4jq2srcn3+deJAQ3TBGIp4J3eV+V3YNIK4R3pKo5yxddRTRkqTudrRivJywzC+H0bz2/ABSnPUEyRyXvL9hRaBaVadHfJFVjgGFwL+r19C31TlCC21HFNoiAYxiRD1REkpncfv+dAQOH7B3wO5H75plmbMIzhBiYUy9EsrLa/d/Jo0nA6OC/uUEQv07hXpXAX7NYCzntzP6giNEDmQ4mDL5QTHq8SG1g7KOwCsBHafHzrowD364JS9+85IJfcf+bCnTfKt6sJ8LOAJrm0BSum7qErVk/VKewbUw/impQ+lbU1eCJ46OJDlUNOoD3uN+68EMAQRZnd5iD2LefMldUtU4dK3B2vxZ4nDMca2kVKgTWSVXYBYWBiBvTPaEsSg+rWeWxMiPZezvBt26U0x6tQ0CYdV/+TpuMijD3RcMze1hzb5wp1fApesHbSPrVDUwqgLddKGUoYrvl03pN+CBCUo54foxJPC8Y55iwJ+9c7EyMEh1g4cc/eHRwks4Z0zY0/CDiuvvSD7QZYJvgWumxY6Jj17wb5OY1BKFXUr4GvU8qQBFhyYlBVV0U4=
    client_secret: AgCbj929Vl3Pyw8dULd1lvluK4Aq76l9ZyuNa6dXBkjEancFZEfhF25nKS9xYThsLZrDLpolf1WIzgT3NXEda7ztkRhRwJi6yOKJQjYD/E0m5Hi+sBtlP8ffPVq0lhGCDs242f/VZx/rRMed3YO16SBU7BGgU7zbij4X9JyaXkd+vTil1mF0UsHK9KKGqEaWztzv2u8qVwzZTIYYyYFgAiSMPPKUL30PknMwY/7fTrlE5A7t0d7Ku+N+jKpaBpFZCS/yZQ8s9W8d+/KdvS1HhhfIbd+YpRmfAZUmcGVZp470mBq/OnmN3jc6bJLLBP6dUrKctQ6URJ1TJI1t1d0e4TiAZdP0ilmYC9JIfryJJpzp7EnnlKkB8J90P7x79Ni1Zl48Lo+f2W/p9jV3UXlkfRCYJ2ND+/dIB1fq2FAni5P4wkBHlIaPaOwPBSNjA7ufXmh9KjbZmMp9BwQ/G2M0uo7pLD9PSQ30MkWBoabAsIe3lQDKey05Ifuima1yshygxdWVOsysU4a7DP2Fr5vPO4nL9cARdQ/tsnJhIq0laKytYlAKhRm7G3IcO6kggv0hHAKokpLBSIuL5IOedTUUshLb8QTWQGeDF4jYmhIgjE1in8X3bnoVsQgKjXQRXUmSRfY8iLj90euyXvaaJPh8FYx3rFV6hxI8j18HBeSyCMoERJBOob5Z6ccTyXyvbqzOGni9FiwqwQHVOoDcC9xuS6BsdJ6jjGI1kNEpiIaTjGG3VCfsbXgojPvrh3t+Tl5QGzxKACCQ3PwF62YKgN9+tV8z
  template:
    metadata:
      name: harbor-oidc
      namespace: apps
