---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-trivy
  namespace: apps
spec:
  encryptedData:
    gitHubToken: AgBTO9C0MGqrFfHHJ23kfna0P22LseAzZf2l+9eCtvmHGGe70XtgF4BCxV8ZFhwOvjvVmadgaKe1Ad9fupJItu6IjObDuhbTHIcMcvGYqgjbODNKFcTdWGAaP1GmcsZwB29jVX8U3C1FS5bZnpso/5JsZSoeMKw6hHdN+QqrGXtb+9nR9rWzAXhyeqnkscdwmquEJHSOxI20U4I3qkO8A4QfUIaFPY3mDMQPUfSMsTtC20IGFkzDDX0GJp3o4ZH5ZqWRjc/lPDzp3YwCmVLzNcSANvkvyfWt6NVJtvyBXhkL8r6iJQD9aiHQfMXD4iwLoYt9vjV2oiUi5eARjjYlvvfmwFta0YCNKb6myGeh34ahUWX0uJnPCP9kYK4S3ykjTmy3Noj6zWMf2K31OOtKahVq4l710G6bH/fbzKKRGzT1B0L6VsDC9O56341EFsaJQPi8g5IfI8ybAYm68rXDUGfBiNDgyU64RD162r3GK5SSfatFWZHNA0qGEID0PwX730PWZo27oVCH8MYHWBvmHdsOP65UpyTA5+0IVW6RNVQqBhcjwIgWrwvgu+SG0GUvxe/Iq6NmM4Q0K877kNqgOp+xNoISd9vNtJHuIaII66tW58qcRbNFbZ/pFqM74ergN+QUnm6H8M39L10JDDGW3ctaQ/XVHQ74nB4m7zygHB491FuhgR/SFX4y4XlmV2FqAoQ=
    redisURL: AgAbCCyv/qGRuW3g35ea0FRl2kJQ5r61UbOtnWilqx+Nx4KcsLKZ5YgnWwFN3PpLfwA9xlNzxJIj8qFFtDNkibpBu/H4iYCwAAH2OkCgZGrX33tbxeSdmdLP1HWx7k05B2FqIQYUyXAKqhQd+mQXa1lae4FCQ4YLpedGV2RHcalIXbS3wfCjDX4vOUfTWiNjp0zny5usBitbwlj81v+uOvvijrO/wNmfqSwiZy9iHWjP4ILpbPgabmLmKOGAK0ylcROhtzw8etk724SupKWj9+hnxw6QzfbOmoC/GZb9iZ3/5PzzKM0NTYulyHDnbNzmS8RGowWXsXgW+GEpDdVj3W4L/eejJJXVa7PiBeX8HdihDjwEp/cn+3SbZ34lFItcgYZlyRen9C8xXGLPFpvOJ1KHCVwRsxhlL1B3V53wt4l8lMHsMdUH5gCRzHHSTz0vO7Qt0kxZcnS3OaINep/hC1lTQVHEvUetewfn6BQcOX7lAs1DXVQMiyC0zi8Dr4qB4PCo06z8mjMUGrmy1D2ZJKWgoPECK+DuOvxdwNnL7nh8C7rmts8tIYMtVBEOmDKYpPYXIzE4o5vmYBZMGLs0JyXdoF7ESZpeaIvv9ICdhAV0sSBcYfRGoB7HfOqLdd97f+AD4oY02xHgPB3A20JEcz4pkjhs1MgMhp4+DuwAl2JL8FDk0L+tXQLsQv7vNRKvHO+AYOMSBDQNZ+QhgEhmf+NwgJVYJ8LevRZaQUhVH34RyDaztBHTucBEicDLfRiozmvZOzBqDIb4sTyiFSGJwHfgXaLH6PixhTNyK5M4AfhLmPrOGTqgx4LfONvvWUZlGhOEwTxWQVAHu3adnFQ=
  template:
    metadata:
      name: harbor-trivy
      namespace: apps
