apiVersion: v1
kind: Service
metadata:
  name: opnsense-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opnsense-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies: [IPv4, IPv6]
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: opnsense-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
