apiVersion: v2
name: trivy-operator
description: Wrapper chart for Trivy Operator security scanner
type: application
version: 0.2.26
icon: https://raw.githubusercontent.com/aquasecurity/trivy-operator/main/docs/images/logo.png

dependencies:
- name: trivy-operator
  version: 0.32.0
  repository: https://aquasecurity.github.io/helm-charts/

keywords:
- aquasecurity
- trivyoperator
- trivy
- dhi
sources:
- https://github.com/aquasecurity/trivy-operator
