---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-build-user
  namespace: apps
spec:
  encryptedData:
    password: AgAGEIRJNlWdwEcEh+WQf8+RnjWFFeXII7nkCTHpRBKiJJ8rNgKsKw8N+2TjR/1xnYylrgI7uPTK3vfhPLq5jvUDGRqvqCZmFEtd/zFH4iDmLvfPeIn+GqZab45B5ajm3pT/uphSBCPBwDY3EDC+amsZ4fyuKyVIJTs+SUo4VqjKpKi3DXITQxJQlU4ChFlW+U0CnMwsmQbo9+68UTlpKpHOuk6ygxg3Cz98SYEbI1LoFGINe6RK3ZLV8PhTsIGlqEOesdhxBWPGwqof1LhtHu2cuosDMIdEVfncWsjttlrL5/HAbrt2/MfbINiOKp5xDRJ4YdXe0p8fQrWwFIWySE5SY9nMdGGEW9s12yrTjtMcTJceqn7nhSX7eCHSCS1k73qW5e2LoQWljrJRx3sfyqVmWGGiPPtvmVjuJmT8BUsS0qHHA8O7g9KL80pt49wyQHLq+kX9q6lFasG/u57DA8imHcbEaMhOHKknfWVURlgj8EQ6iinS53rsAo0FTf3sqlpaqyo/9m7nFp0WZSS5VB6VGLKHnS0+fI4B362UKOLNiKIxC/cPry6mLsTeydtcwRxmU0pdtRliqW6FokgHRWvIQjbLu4irQ2EHZXw7CRItfjRZjLpov5a6PWetc9LffdGdS68+iG1KjcyNTfTacFurx/yGXUToHKXo4siIRvS/q1fb39CfVIKjpuujrLwLjn0=
    username: AgChtAwhbFJP0IC3TNeKmoU22rw57eg71t+JWH0Ccq8y6/pyNEEt00jKF6h1ZlrWgkgK+wRazrb1aNO7Cys51oQsswZn9O4w0SJtEnsvHVoYb2wNP+URiMAzMx2CwQtbisrfTRGAeox/z0OAj63QkOVZL7VTvKSv7jC/BeI+8nrxoypgdTCdNgQD/Gzi+uByQ8v4IfrOyj+j21AQh/UjY/Cmy0WldwBfm6nS3/d1rU8K5kOQcAZPp3WewGjYpUuorHdufNvF0zomWfYJpBJQW8z82ymgUPfvrfUU/1lTrGhn19UiZGSES5wSoD8uYKjPMQRi7lHfMc4ZYrPUQq1fh1zKKjGgE2XMuglO6eur5hIAo/6vg2s1J2bGJXf5PXFP8GgroTSEy+J0eG+ORM2a4GQV7IDOBJoKgklIPXyxxxMwxZrB0v+9YnBcpAZbE7j7lpf+7PCkqiOqTlgHWUOhQXSgmGHutS3+BhAQ+IGfjNCARLyOH1HTj33JOc9AVHL3R7y6hFHY/VIZoVlhgJjl4nKIvuihYHIyqbg16oQnBL6KQtbLt10AERd7cbnZp6+DInLUhJag5ShvUp/04+OeUVXajIFTHK3+SOuaagjq8jctUW9jt6YbB7SM+YiFuKPOvnPEPyHlxvOEpS+VynVnZiU5HR4X0MOQwE+/EdE7XbBR3qcuDlU5cM7joQNn6dAA3P80TUXZB45C8xZaLXs=
  template:
    metadata:
      name: harbor-build-user
      namespace: apps
