---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanopy-daemon-api-key
  namespace: apps
spec:
  encryptedData:
    api-key: AgAmLK67r7mR+lv5OM0mX7qU5yP4We4vumMZwHwf0KyNqLltoSTJo5UcNH009IUHR1pt66d7LxHe+Weh3OWJ7LviFUXFPcnuUOv3V8vyc/aKS9n6540SxtuwdUAbWAaCth4+MYQmXzbMQBMIf6lXeOqTNWkIq/sOnJV2PSep9xyndnRZ8BbG6w1vkbciEQ6yE+s4cBb/UP2jsdlhfRiUGdenJBs/wZtiigafIQHgigO47rO5ALtcxt6cXaShQaAr9VVgox5TjtOkIYASDSUFVdtXOZlGcdleZemWymTV+F1l8SieFYrIohIB8ZLLt8Cvlv/apCGjCyzq4J09emZJhmz8jgW7tCHTmxrNtEeuRq3kO+l8jKACldIGx/T8Vp5hRI6KVsgFv3zIYiYGBShLafit7G78flV89o9ZnqxdHLlo23bGka0f74Ik6wdGtABrNuir9VWcXcMyYc60JkjZxRKxz+JJAIu0xVrJt8Yk+uQ+lvrLaxfMWhdQvX6FhVc7IK6VfuyoG7IkGN82aXXV10LcMnQ0ZNQo8RlOCDxLD/4qYcsqPDlHNrKjUxjqGHgiG1fi1sb1Pi/9BydHL0ARle/38MLzTu6ym656UtO78LbEKwyhM47tVghIwn4hIP7fu+FsQUQSoUzLFD2DWhDxaxWNiz2fySUe/qLsfVgCLErp2Ck/0oLp1ljkk8RX3bNyDIgvhHLlPBFAqWCztAEYxPgG0IuUgvm/CmLFtlybSThhZRzq2VLY6g==
  template:
    metadata:
      name: scanopy-daemon-api-key
      namespace: apps
