---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanopy-postgres-auth
  namespace: apps
spec:
  encryptedData:
    uri: AgCYkvy6hUipcZ8nOkLjfx/X1VL5HqpeZLI/nIHDNsb3pho+yMIoVH2CMlgTsHLORwgQ1UxdodfdSo3hbxYvV0THz3LUeXLzH2hkcagxw80zOcZ2ERAx2X3WLnGk0f/44k4PDEDL4c4vGb1X3oiVVs3ToS2JlyrgnzxTsBvWYyCwnTIpL7DRclk4zNQurM2qoB+8eWEuUxccVy/391mSzc7Sej8wTCPuvoT85ORHp/vsHEQmfnttPg/9cALlxFbWAXL4x3fLsHUWDTZTvCIh9mz/ts9ks9WvyAobm87505WDiu5swKmaiQCL4n1w1QwR7ItPO7JthdijA9D2pVwsK2oERo8B7+Xr0S/HjpKz4siG6fahNmQ5WECCgKXRujf3y0uTaGO7bFz+JAOSTIsk+ixWvuRO3Nn+22rnJKEaE19COV8v67vQmiPIxvcnV9Y9YZ2F+23G9Xj5pMfruJjyhtgI2bmT0Fr+tAEh9ziqioiXNM2Mo/HUvqNdvyTILuqPBfb36d/HiyTUJvI5YENURRvB20pchAX0CZEaOD8iiBJCDlaIvk5aRjNBqV42wYpq9ZIYWjCcb+aMSXp466ajQj77jONupL4orUe8t0na+rGDZCpsdlaz2C6MGb4zj5gm4Rb3jQJBuFoO2i9ydJWxlcGYXiFaeKWHf5NeRtVCNJqCPFeVzXIDcNlzHqHG/t0cqKSCiQMhVMsPCblhRWVbMNFjYNr/OZ0kSoPt8PZjhMr9kiCqAOKHqGtWn3z8C9lY3y7C3sbT7fkOm6CoIsSRQfLXIcq0hPn3dV2rvjYM4zJFmFAzuKlfd1jQqDdXx/SFTOIXbaEO/dE=
  template:
    metadata:
      name: scanopy-postgres-auth
      namespace: apps
