---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanopy-postgres-auth
  namespace: apps
spec:
  encryptedData:
    uri: AgBYziReWFXIMnz5Xr+6mNbFDAMj7XbUrtAfvzOMNCLXgdE3RFzdxqzmlaK1XwsZ85NdKxHNGfxc4oA1CPcWjt0wwdcXw0tFvuWLLHw9xGkNxr0kgFM/x6uA79IR9l+WHpQTaefUZtpV0ZSAX96cB1cQPom8QpMCzEfIpSQubaLC+enHYasnYzs0419ie2x9rKOfPBfcihPPPSK8J0y5saTmT/xSTUJ+3R57UrkS+RXUrVUuW0djO2W2aPDKrmVXIBMeApPrDykA7p9yTyXmIvptcvYOBF8Gsi6p4+AQJgwHkRo9phtVpjTIVKT5/qwLtKVeAX97F3uD/QOsoiH1HKQzH4IMYqV1WbxopUCrGBk6PO+JiC3OoNZgdUdAjH+V9x8mNU4I+48l/aib7gRZWh6RRqCdyKb2Mf3SbRcJwzI2iGt4vwbxh1HLj0xr8Wlxow3buETxROQ4B2Hxdc0cW3CQ/4yLKzqKQZdk7kAn17pYgkK2AM+FUZuGNHHvZyvReassHvAHiE0iH35LYwxYA3kgdfqkIEuljU1cMzskxb4yOnrbq+q+jZMYKpuZvo02bY0zw18Xn8jWmQcSTPb1iLonK8Rw62Ik5gaTMGSxE4uRY9n77waVxcn8DhROdvVdxTvmbZaA/gpymCsc4DLZ2M60scX3Hqt+oWyW8X2jkfGUrYni0UoPc4OWTuiyU1iDGGzYbBa6FyHRLf5ek66bq7YgPH4YQjbTR7HXhAHWBH8WWF1tHGVSj01piMtTtsLxnAqFtcBC+opvHSz8WmweukHav02NVyr6XYoywHuWBASh080ND/iYS+jlxII0zE7khq3xqKu2kBXXaS6MrLrP0zPnHyc=
  template:
    metadata:
      name: scanopy-postgres-auth
      namespace: apps
