---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanopy-postgres-auth
  namespace: apps
spec:
  encryptedData:
    uri: AgBiWDBEz8tX/RsIn0Pnk6kCgxE68s7zRtxAOUmpwLaSuopIKwTvtw9yvuy6Sqbt1XZMQWoukvPJNuMSPGMPdt80ai4A1CIHdRR1UuqAA3wpQA7a/GVM+hcrTuUeYADYpCUzj8hrBpaLTqP4jXZnR5+8d4jz0sO+PGCUY18iVTlSB1veGUEdkEeR4caHW5GzWOGcmwlhMns7MWhEKnpJeSTeYr4QRUBG+Gry5s+KGaQwMjyesD7QpXqRh5fNAyTrz1HbepeeKWPVSivKH0XygnVVQyJpK3T9Thdln6DDrOPSB7AHr/Ln5qQ4xnEmDpBTPZUKy0ajxrjTrqePX2UiTWJwIEmMZxCN3//mpEMGB3vO/+dW5chM6LF5Jfuv2+Nl1vb5cXBhPfRZLFQMBM8N6hvAo+tqFkxKyv6CSowpT3gTQhleyNec0iCV19QhIsgy//cBuV+VPwxYdeaBKxgWXPdrNvEm+ox1YsJELp31cRpKQC3NHOzSrkWMjd3P4JuD7mtutwZPHN2TSldjtdjHJwaNaZJiYZD21imsHGbbhyYFqqWPXAfTY+sOPhO1qGPPT8IASEjimU5DSxyN/IpdhYpUcRxcT0125i7SQ0xa1vs+qhndAQ2JnIoT6nUQP9eVKsB7uc5PcklEryUkn8HeZ2tDJLkOSjlv/XbAbe/gOVppRo9kb97TIfp9d83RtguJOlmkrXrtR37a8KgZUUA8uy0cqFYl9CI+hKKJ1zcDlaRE+78P0Pq/+6yoBlhktFThwzQ6i8Tk26CcJF9JyY1c3scr/XvZtY18cMgvjOo15e1qOZNfHDfu3+pJzUqGErSA6GxAzEHOoqkG6T+0AIuvf9FyD2zBrLx0t3pGyAI=
  template:
    metadata:
      name: scanopy-postgres-auth
      namespace: apps
