---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trivy-scan-regcred
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgBOV5C5ovroOQpo+JX567KA+pbjOLuQ+xy72uIrUnsr5OAXzwL7v56RkHSnhSEncHCX5BTEi95pBkDYmYl5ENRuwXRQ6iVPMwz1JPrIDGZaNq9hU1NpZMpteUujpSxHzvI+70YDp8r1MoaOpniXwtyF9IxgUYIFZkdTfsNdw4skqiXpLtub1ZD9kTWxZ8/K5NCGpGl3LC8fERahpLjqRoGf3qKYCCLtCMVX510n+/utbmuQQ3ji4OjUEcnByIz2CLyGVRkrj/Bg6luxoPBC7cvTEaOhwUgbceS8YlcR3grer3NiHYJ3ERIgNCuXA63BlMi1VEWgRtgpylAeSlOzMgQ/m8FuC7JSoVrcFo9NMQNJqLQSB7iv4YWMaqNBUQ+vgb2FrBh1xG3c9ukP9bhftpbOxh3acwXNS4WUAnTEZ7VykrsV+lCNnj/79mLIwbAKN/Z++wP9JxUrAS+zGQarmJXL5nFZKGkuyu/UQARsmhiD21OY86tDjXsCJjNTIGkaMVO1XOmddXugmnLba7qtfWPQNWEP4cuLX/8R17dIjQlGZfj+sTe1Y8kijcGNSo9IZg7rtZHRvl+0ExQ0mIWtK+x9hB9ycdjHN7YGQJml9TnWgRnSxfEXWzj5gpI+O3sqrdURYUDRA0CqLfWaB/tBBwn5NtZRuBsG9IdKyHB6pObQwsgSyApUL7vbjH/2JB9T8p8fnzRwgEONSVYnVFNJxypQw9tASggI2fCnTw0KpwunEI2LY/GZXKoDSZ7HtfApnH57F9iMLGSElAgw5vd2kJ4Ba05uK7JdqZTGbdVI9vmy1x0NQT9Dg36HYqv8YzgqXiA8pgrxfa4D+US9qrXOa9pD0hBF6MygzRoL5P1C+u5rkvdObtJy1JwAUXQl3NHouz8IgUdU5c9aVMG3DgAWFEupLy+E3IvhPi3BYZxEBsKay42GZR2uFr9DUB4iRi9uCK/xBMpok29qg0qxP8RBZd8=
  template:
    metadata:
      name: trivy-scan-regcred
      namespace: apps
    type: kubernetes.io/dockerconfigjson
