---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trivy-scan-regcred
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgADFGV1nmpyZLdKZIiiBij3WJN6F89kPUDegeGhfjloS25CvRPqyiSuJEgabxZ2FM8Hm5SMPR0N10ObujFE+O8CVLo8bz4o7dUrsxLFY5iMGISXfUelQbic8DQzwwxZkTgaG42Mh8dmjsO/GIoqzA+pogxXoCvZTO8cramZeEARcSi0L/BmhOxujc2DMcMytmtlsFPH6qtfp1haU/vUazF5p7Ovixe9ZkdHQy4MiVmhkmfhwKvmRrK/VRTYzybgE2yLEA5xRT7ECrJj3HzqO/cJN8xuym6RPfoKvlp/9ce0ZzPKdDOUFA0O3A9KqNV3pBCelaqEKmwaT+ri9ah9QmkGtk1EJvvaEShhuR4XUJ2jh9EzuAu1fRma92rdyXSmpw7rBxwS41yyXd4GFaa5KBugcSes5tBFO5BU/TLNfh0sPj3tg1nJ3SEjKGIzJdMu1bJY9aqZVh/h6HCkbBkNUMajoP8EDVu98/0Df34Sg1KgB6Rk7ZvQHXyCI4Kk/L6m1NBcKHYdpxdADMAjQ8XHTJ5dA7KPkSoDnAGsQJdpCVd9jmroJgpVKllIylGzdAac7h1xC0Dh6nDCgHKz6Y1jIbYFn1qCJ5dHfE6dPLqWgUgDqJ25tBHqebK84HCryxklm9wlFZT9eVpC5KX8nUFhOZoQaDvgWBkOkScf2bCuV+XGwFsETat8ArWW7SVt1lNFPiBobl3GU2ShW2/xbMaB1gzsq/dPfjufty6YNCG9BIAmNyGt5mMFEmLfhc4h3ln3wYBeVZZO5hGzRg0vH4La6Taym3SdTxu4+25hOj2YUF+2i/59xDWBtdPZX4mDEeepw/zuWTyVJAhVDwEkJCDwxmgA7IngGUazWelLx4AoOVEOSNkilOdkUr+q5zN1Gx8ZoLYfnFOWiJ9B5B1srcZqeVkw4nALzSG5VaHFA7dtqaWgoafzJvcnIXqaSk/SmF2Z8W0ECSOHY1Vqko4=
  template:
    metadata:
      name: trivy-scan-regcred
      namespace: apps
    type: kubernetes.io/dockerconfigjson
