---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qdrant-api-key
  namespace: apps
spec:
  encryptedData:
    apikey: AgCb9HVA5Ih6wPS+Ti6MOYbcjbwmcitDVNLFonLn+BHZG5+DMx2fxwL1pbtnlDdJdk8Q+9a7lfGPo/Ox/n5MOnznB3PzcvTn2JSjaqNIPCuEs3TdiajM/oH9roGEfV4w9Whozr92pCqW293otpf/nIO0vLcbQRzMFvNcRcN800AIR1PBEDX1t3bIb7T3juQvPIGYAVwTTLkLbkk2hDBvNxxbZm3k3GzH74uWqA4VjOtslQPuAIQzIUQY7nmdiHoX1PQ9q85bWOEk4smb89198AG4rKC4MhEwI/fB9i0KZInHTMc+xJX3vV4kFvrl9cN4QBwLJjXVB33OAHWNwl/kClap/kZ+vxSNkCvIrnltcboWTuH2x8EWcN/NwVV4GC8MKpU8Qx8aavphIyoHFTx2zuaUijjHo6Q/SmfzUoa2oYFHsydXQCwTUGSFJNhpl8CsWLsTT+HZhr+rQoPSyY8yCrm91DL4dKmUgd3qIuX+jKR84De4M+swUqXP7RoibZ82968BGtHXYJJ/GOUUrw9zyceox1TOqAslz16EKV+6nbnxqvaVXr3u/qaIKHARDYQr+3sKLiqBqH1jC6nSf8vNcVIFLBbZZIi2SeOGkJ49Bn+VoNZ4jVypA1vLCKQLP0M4ZJYbz79kUHtJwXTip209NbmnDfkgcbJt1OBGcvgvYXjUyUE7PN7z+y6eNz1o7iCA8a9ZDvjMjgwKpw0fALo2M6lgdlB7vTYZX1y+3orq8WRQBw==
  template:
    metadata:
      name: qdrant-api-key
      namespace: apps
