---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qdrant-api-key
  namespace: apps
spec:
  encryptedData:
    apikey: AgAmDwMZeZx0Hld/cIh7NyZDfqeXbPSf1xHFtffl1gv4n44X119Vd57qFmMKqS2+xcHZgORpn+yV4xoGX4ADW4nNTMkKQZiFcZbr+saYqPp6MVo7J1gudNmKqp9mW5Wkso+IGlyhYCnorI7AYn5ACqFTZQp/h8D3KDy/BOk/vNv81jHXEpFs3HAexZ2n7wruEBt80kYyA4xpLO8EEG6RdjMLNBTNPukyaC0hK+qUv8FUthf5lBL7/E0MB4espJGkkvezd0jejZkKJcLLCMQSEX073msS2wsiX0bqNtlw11GMzJnRSJcOFU+nFtS09FtVANqfo4deIFA49yl4pnv2/bicutbcLCQxheDMHHHemY9qah0SuvYta1MWNVOuW/Vw6va9zsbY9AyGdwhfVnfAMDJEWItBucQ9y6qhMDSxhBBCHYWyUDo0QJh5bpKaHmy1MQXsrjIU/Owmc3eRw+i9mbP6H+vprQWeZofCIbNzYZHxjT9RllsriJ1CGjHQ5Y+UfrfiPM8XMiJN7pk/FHVRiZMu/K8Ti+XzCdTuQiVfwDeUegb4OUMEqwaNcZFOjd+F1VHGsmRa2/DddetBbLB8oHw10th27j0vUji2rs+a99nZKjMvHAg1Cw77UxgwmhgpjmzeM0FjokJkPndA9Y5AAPt9nTQmrISMUJjOETblqV8tbHNuThvKTWqzFAB3Nz/0poyRb4dRLAzgS9/eFM8EQudxVvRhUwe9Zyy5ukoQ1nvmQZq58YkunHO4
  template:
    metadata:
      name: qdrant-api-key
      namespace: apps
