apiVersion: v2
name: cilium-policies
description: CiliumNetworkPolicy definitions for cluster namespaces
type: application
version: 0.1.26
icon: https://cdn.jsdelivr.net/gh/cilium/cilium@main/Documentation/images/logo-solo.svg
