apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotify.fullname" . }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotify
spec:
  type: {{ .Values.gotify.service.type }}
  ipFamilyPolicy: {{ .Values.gotify.service.ipFamilyPolicy }}
  selector:
    {{- include "gotify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gotify
  ports:
    - name: http
      port: {{ .Values.gotify.service.port }}
      targetPort: http
