---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-smtp
  namespace: apps
spec:
  encryptedData:
    SMTP_PASSWORD: AgCS8mDknzWSC8mJ2O+zD3kst0o8A1Il+4JeI1XNszakVwUVCB8hjteMS75/RD4eOnMpgjNNv4n4bSgjbMNL4TEe4f3HC/AZsJd2BTH7+3GTUsUqJo6QaaFhx3LR84cFzoBJRETULTb1sD14zY7DQb5GALT4DA4VlsOaogdhyM++zzmbvfJ2lw/Ofso+7v3j7SQ+usceeIirXQVoLNU3nB32C9pWnIkkeoIIB/Gas3VGak+292l09Vr04mZyldMMcrZw6UrVe4lseHr6tqFpo4hQZjzJ1ubhE8zWTWZDuslyQnUlCr9V0588cCvMc1oTgEOl51Psj5kFDbQl7Q7JbHfiQ0nnqMa4gmcMahVA2O60NvjEjkV3uiV9n4F2L6Kx1Kao2hCHptS5/BzJV/nvvN9r9QhEI2fAIfnmdoSUlMMb7K9IKXCrFTAowqoTet++9yAu6BxDJGPqZzL2Yhk5oyVOpLVTDpar2BC2PsCi2K4IWD3lrl9mHxuPVG4AVpzSwwW9eZbGruchczyWggj6NmoWXAH87sw77cr+fwRr/tTx5/tNETC3ru2+Rtnsr1qJWccvllub5gbt77LAccNifbG+vZrUbTKqi8IcsQshWO/cpB46CaH484BN+V8nDgktZV96cpOjWSX5jJjd8Q6JgM6F7eBgJYOn4dKOsUYLSgy9s+3I4RTLufpgqfScRwBk6bbPhA3pdKIQfhO9hYfKEg==
    SMTP_USERNAME: AgA9aDqPrwwDyLI7eEuI5avf+Ftjkw/aXuUwZAtvj45ncsEM9uANUXTdHTD3oVQec2TpeZeFrLqU1D79Bt8mED4CbH8GuXg19xjk+SABNgvgbRoKnmrW8siOlj+GGPDuDiBZePJjMKPuMfZ1fxUb2wqf2GfqX6sv0vJzki8A9Wj+6Ut7BCHRbyQBbJbe2Aza8UEiiIh30tLjcPqfgtlqHyLHspYDDPUaIWsWn6Vm5i70pLnmLbP3bXR1NntM0nRjDJ7zW6asGF/bkDE8HSNOuYZ0R81kSthZK9N+mGYcTaGAbYhRu7qyEFz6DvPow9XYKIaatXdNWRAaDb407A8Ws2UpR+2sxAx5GmmkQH2U/ObecfHtpk9B87axbIbX8MRJie4mIqSI31rOC7Avz74YTUwQ0BkQzW64NZ6k79UETtrtrlEf/E6DF0HvGLd9a1nltnHHOhI6aEl4X8MyrCKIQbqYx0lCBfFXdD/6pRpcSCCBM6qxwXju8k/DBnzlUypeyGIZF9em6iGsURNxcwbZHorv+SjIL0ckOfoLPyPHyyu4D57Ubc/iCABdiNxKpwc+aLJjDk0z5ay7kliq2NhiqF3qxLGHdHIPoZgak7Fv/xQdqutyrHHVL0+0Ic65W2ek7Zg/2X+DSSrtx3pkNRBwFmM+yI6EXoKCextnNC8+PndcWKQEbBIb+H60evtq8oBpC4QhONu9cfJH1BoRlW9nQw==
  template:
    metadata:
      name: vaultwarden-smtp
      namespace: apps
