# apps/cluster/sealed-secrets/Chart.yaml
apiVersion: v2
name: sealed-secrets
description: Wrapper chart for Sealed Secrets (DHI)
type: application
version: 0.2.2
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/sealed-secrets/img/sealed-secrets-stack-220x234.png
dependencies:
- name: sealed-secrets-chart
  version: 0.36.0
  repository: oci://dhi.io
