{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: authentik-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: auth
spec:
  type: ExternalName
  externalName: authentik-server.apps.svc.cluster.local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
{{- end }}
