{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: open-webui
{{- end }}
