apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ index .Values "open-webui" "persistence" "size" }}
  storageClassName: {{ index .Values "open-webui" "persistence" "storageClass" | quote }}
