apiVersion: v2
name: garage-cluster
description: Garage cluster instance with buckets and access keys
type: application
version: 0.1.5
appVersion: "2.2.0"
icon: https://garagehq.deuxfleurs.fr/images/garage-logo.svg
