{{- if .Values.apps.tika.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-tika
spec:
  enableDefaultDeny:
    ingress: {{ .Values.apps.tika.enforce }}
    egress: {{ .Values.apps.tika.enforce }}
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tika
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless-ngx
            app.kubernetes.io/component: web
      toPorts:
        - ports:
            - port: "9998"
              protocol: TCP
  egress:
{{- include "cilium-policies.dns-egress" . | nindent 4 }}
{{- end }}
