apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: renovate-operator
  labels:
    app: renovate-operator
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: renovate-operator
