apiVersion: v1
kind: Service
metadata:
  name: {{ include "tika.fullname" . }}
  labels:
    {{- include "tika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy | default "SingleStack" }}
  selector:
    {{- include "tika.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
