{{- if .Values.namespaces.kured.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kured
  namespace: kured
spec:
  enableDefaultDeny:
    ingress: {{ .Values.namespaces.kured.enforce }}
    egress: {{ .Values.namespaces.kured.enforce }}
  endpointSelector: {}
  ingress:
{{- include "cilium-policies.probe-ingress" . | nindent 4 }}
  egress:
{{- include "cilium-policies.dns-egress" . | nindent 4 }}
{{- include "cilium-policies.kube-api-egress" . | nindent 4 }}
{{- end }}
