{{- if (index .Values.namespaces "metallb-system").enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  enableDefaultDeny:
    ingress: {{ (index .Values.namespaces "metallb-system").enforce }}
    egress: {{ (index .Values.namespaces "metallb-system").enforce }}
  endpointSelector: {}
  ingress:
{{- include "cilium-policies.probe-ingress" . | nindent 4 }}
    # Webhook calls from kube-apiserver
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # Metrics scrape from monitoring
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "7472"
              protocol: TCP
  egress:
{{- include "cilium-policies.dns-egress" . | nindent 4 }}
{{- include "cilium-policies.kube-api-egress" . | nindent 4 }}
    # Speaker L2 announcements (ARP/NDP)
    - toEntities:
        - host
        - remote-node
{{- end }}
