{{- if (index .Values.namespaces "sealed-secrets").enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  enableDefaultDeny:
    ingress: {{ (index .Values.namespaces "sealed-secrets").enforce }}
    egress: {{ (index .Values.namespaces "sealed-secrets").enforce }}
  endpointSelector: {}
  ingress:
{{- include "cilium-policies.probe-ingress" . | nindent 4 }}
    # Webhook calls from kube-apiserver
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # Admission webhook from all namespaces
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # Metrics scrape from monitoring
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
  egress:
{{- include "cilium-policies.dns-egress" . | nindent 4 }}
{{- include "cilium-policies.kube-api-egress" . | nindent 4 }}
{{- end }}
