---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: apps
spec:
  encryptedData:
    client_id: AgBrEkQQYghG7IsBEebOjK3kMRQPns5n/DDmm8rN7X2RiBj9hJw0+b6VIfOlEAx1gv1WA/2JRylB9BQMEdzP/AAvvc7H0qZHPF4CmDHXaZAXirmiposI5Fj0/UulWzNCHKqjQdCdz175qVHBc3XiJXY1Si1HAntxLfa4AoTwJSsebevE/pha4E5Vp7XUNsQQTP+/TrVyO3TPMekgOv5RhYiVgIAgtcmO3kt3Gtzlngxa0amoSBH4ImBrA2CbEqk1mO3DgjoHpt56PYmDVn7HWjaK3E7Vjm4XGITNi0BLo3ec+SkBJbmkHVj6+MC21nn/4ln6TZEELQdPLd5jKIu7k5v+ejGf50O737bPZsHwcACrnXYX62uJzXZGD1KqwLYviBhqkFH7xSoyVRKNlsYb3m77Lw2mVCsmKsmY5wHGGFLnTZajLODL6jckCbHwq6bJOS0ArjFknztOtl5b8sdYlxr7HRzHtJAk5D1x72kynf36lsOY5Q5faI6a36+G2NVAWgIMdB++Lkak3xwSHOyuRLcfS6BXbnFvrzHXRii1fZ/Dtfn3V1wIvXvYbHV7UWR+zPQ1g6aPX0fgD0eKQK4VUrdpe2k9nX12FEcRZmY6sEIVXNAd3k8URx67alQaYnic1yk3SSubEGRfMC1SjeVenGI2EpUiSrsR+y5RlQuUnQ9asDDrcfiUvaTUhMn9kC78AJ3Ln0GrnazLwP3x0aDgu0fgLQ4D7dKI7Zqd+3i1v9MXN1hE7Lg=
    client_secret: AgCOkMFhARCzspAvZYLwsWRKqM8uyJfXa1YVSY0vsf6wwXXG3sptTgB/VHZpMjlziuCRXkh4DkDECyr118Dgxz2v9gXFtE1GH3TRdwQfz03l6BdgBxhoQV59kYXNhk0Lcnx2VeCWFXVoxZwBwnNIS/VPgEX83TZUtAK+96vXG6cSdMTnMoN3M0zI+H1jL5xhDR8ILN1SxhfteENr6YnTaLEt8ouoXcT6Yqtu1Yz5An86DOLwn22pMTzPOrq1aEeA/O9pgCdDKccHTKJxp9QH2hMOy1ZnrBmFXRW/m6TGQKwSCPTBFeZpK1a1bx0lgA9Vl2tq2b2m3BgiQlsVi4bqSnuZYxyjjytSm4IrkpzzkgfNyigzeXNlOQnu5howzCrhHzF1NSkLS1Wy2rANWefy/7ov6hzqR8SGWzOJP7sJXSAJQOR6RRBgDfpm8RWIz9dWI2sKtiCVSTYRV35rneQ1RWmoFWwsPpCmvR97cztA48S/Q8jW2p4H2Zqmmonss6k5UegQvFkz1WozkMah4BpwAse+eAUOGSKCEfa90l7VmcPY84vg5JLp1VOxa6FMvUhmk2PwUSxcMjLw2NQ8t+v7lEq7tX2MSMjtuOH2+Q24tdePsBXppnsc0wEIoB2/HETnM2lKPopcwrYlMmCCBhF9AMJVm18bET6NhSbzRdllfR8IgKkobXTf7Kua0T+CZaFZZZin8qnAE9rMH2kofKEEpS2h9eBywMPjDMFlHVwrD8D7ReXZcFQN7ocEuS2d8fCpUjQMfwaD804+UURUHO89109L
  template:
    metadata:
      name: grafana-oidc
      namespace: apps
