apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pve01-backend.yaml
- pve01-ingress.yaml
- pve02-backend.yaml
- pve02-ingress.yaml
- pve03-backend.yaml
- pve03-ingress.yaml

# Uncomment resources below to enable additional edge backends/ingresses.
# - apt-backend.yaml
# - apt-ingress.yaml
# - pbs-backend.yaml
# - pbs-ingress.yaml
# - pve-scripts-backend.yaml
# - pve-scripts-ingress.yaml
