---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-valkey
  namespace: apps
spec:
  encryptedData:
    cache-password: AgBvjQG2sOVUziGDxvyMJL2BNzTuczMREOQv4DLOgWqnIfUh5mg62BjM+zsTf/8l42tPk6OR5YhjmwEbnZZJfTJ1tXDsc9ccnwXN9iOYexwoaxexlMvhLvVvw4jEeuLhcTDpbJ8o5QiVIbejzczbzSe5ebFpuUDf0U+FEfZ32Mb2DoRJ5UJ2yk5+0c6rw4mU6j2BHMtb7fBU17HdZIhqrpR4oaMSBgvHZmP0/CpRecggfGYbUfv4QW9dEoukbNPBtnKpbjHfH20rD/AQ9eJ+35LQF28jhVmguBtGP64Uo5z/14ahztC9ZxNM8EHn/cvrmhnDHiZCCoeOQ/D2fxUtbDikbF7a6dQgU8y+UWup6qg9DflGvQRBLPdsbL0uvZa/s2a1htxgFdObOT11Rd0QCIhQb1UWvwvZoISqTXOuR63ESWawP8Decd2dLByfCN2Hp22N8HD4Pc8irP/F9xAemQfBcfnwbG7RIZoKIIj2X+coSNbFq2Sy11Yej/JnP2l3SGFjJX6lwJg23shoSGaR3OFlM7DJ2mGXzWvD/Qy7OGkjF8wLKIngideM1xQETzR+a0njBtARIwTYWsQiaupqynGFx1g0Uj1XUqJ+cYpo+5/fmkW481LJjNXaj8S+NHCTdIZ7dPrGqBZh48ywKgfuMX8pcG84mSI8pLYZziM4BY5lJ1ryKbtqnE8RltUYLMLqIWScWZl6G8QVnXpfOqRMhGFqRNGl6Fx/Z15XdhRzrdZ59Q==
    tasks-password: AgAe+vuUEm8DEAANlLPPuwXxZ/lDtWPKxMEZprCP9vc/FDvU18VYV56dll5hlpcjv0rwtVUdwmSS/nIVytmMH5ojyaKWcjc8afBFPXNJFjmxGTFMK4YTwhI8SAKYYXNmjiqVtE4jxpwdcvMrscWiCNTfOuJRF9WG/hyWWfIeIALQ2FhmZSBOcqXB6rtw0OFHHOZt7ro6KM4sl/wSZFA97PM83fGVOFF9wwlfHbxngnqzUN1rvCaHv2qCrciyocQ5FyCvSXa3QzMoqtWUfKUiR3T8ynJXLLJLVJRdl1AA75qkdxhQF3T6krpuMoTZERVMJiwvODIZQ6zwlEB6oG/H+/T8nxrg5IcCfMqryV9UqEI2jy7OKf+PBp3PGQSA+yqgIC4ejEm3PIUYcAXyBnslFdRC0+z4GNXjBZLcnTadYifaRQ2tnChvJHTiqHK1n1cAQ4Ocwf3GS1DeTRA2pqfTif15onpyACfOevC1hf0GJKO1GIZjFLNMarHgypgqW82d7mnuZwB9emGZnE05twzKGrZd+zdPFt6jzMaKn2375SIYPSDQ0nujvAMS1Jgx/Qa6EbOo3UdCSbmaB6tSf9IDXyzNeUcl9Dp0GeNo+d1f5onaGhDoU+VwSJQp7SDDNbidWl7WkkpmOkhpn67gWePLqOnT+GfFTht7rBYFTxrZ2klYzedVKxoK2aNdqYm2zYMjEwhzumVsacXC5u8lUbbelsHVUMMIgMZqczmUKKQ4I+b7Sg==
  template:
    metadata:
      name: netbox-valkey
      namespace: apps
