---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-postgres-auth
  namespace: apps
spec:
  encryptedData:
    password: AgByjhmGmbZFWJZmqeMzyWewYqZyRXixsePmniRALQ0lM2Xo5yFN6EG3SyOxJx4HKpje7ukBUY5E+TvAvSB7vvR6gXIPLocBXm0gd61ryomzchl71nmb4a86CSN5C49vCYVuKUTozyI3jERq+0HY9pP5G8QYByjjgL3jZBUTMpizIW1leIwFr3h7Lp8nKQUzeXc+xFbR1EbW+p0WQRxxMIn1lz79aD35caSu/syBkDpcELplMCpKF3JnPrTdevZaMwUZPOna4dIJFA8rlvHhlwZPd4tded10m2IaEFx7Jyw7RwzkORp6+73PVT6NuQM+6LWf/IxruYzfT18GBVk+vjoQfzsMmx2OAiIFuI97SEPPrOOwHARkTFjjJEhzAsvfF1DYm9KxKOB92bOIqEFcrbWvqBuUBv2AET3Qr9E+PNAg1DHAleYouLhMwrHLhrlTMsGQcPK+I20b//DQZBpQGZ085QHQGjbpe/vMqEG/n11xVj0wsD7xQarnqr8H4k8kQpyaQifaQw82nFmxlCgZF0AXzNNSaJr6tQ7soe293fRWWi+St+xU8Pz8bHXDtJ5CN9vszaAPkpWiMJ5UyTeZVcSPOcxWS2gJj0Et9BnAo1mnfgnzAd9LwJSWTI4Um4EFfI9Hek+U48d2sNerPcdqki0J5CQw5YYvWCJr3D+hWlGJg4/55RHdxlLPowitz8/7E7alCBHws9Fwk2JBhWiS7D0uO+cMvNHNVIW+VIj+Hr2keUcPjEIi7MXyhB3kIJ21QCmDaPGIzqCDZi/xo7f4wHIy
    username: AgAq2b88mtnGx05QRtlURRv2lpXjQBvvWLs8wD1ouKbijyGBsumIGFg+GyCZh7Pfoff0+tgpWZhUtDazadRyHqRE1gUybUU2nTfFhyyFY6EnKE/6msZLKPUvwI/nPaDYFJUuDYTwQWb1xBrt393uqcjgs9mOVALpo/DkHRjYpk57ABlCCUqQmdFA1K8dGzoialKAhoOVo6L6/IeSsVfm1EVznfPS2BR3rmopRmeyb4wfZ23fASkXYw/aLEaKdeFXfIql5Tvm/nA7taDCcHnURDTNckUDXooGWQCMidFpqI8ewIqlBF972kOlN8xOrcjZpUN9HVfgHXOHJdZCJUvCSK+/A5SVxI/8+JxTCtQnU6UYFOEw0pKw8Bf02m9MzlODzPL1wLpTJIGc2rHGyBVj39c/rODVcjsJS2DU06cK4E7ZR7W2UAQIAZgEvnemaXhsit0L3YqSWO/vr/rT5pWWhDNboMfPUukWGXrFrvaUDHCKk4PRGfElYwGXvDe68kq9kx9eH84MKOTxrKZ8yoCETWMlH6vX3oDVCQ+Uy7BliOZmiNJjmlLhgnQOhXzpCUhVnVhbkDvCKgB3xKCG7w2hbP/fEJNIx5DCCWlux3oS50EuU7M9shnLpzQddzys3mO86FgjdWinuyUU2Dx+MDPCYRPEpESwwaBsJYRzqfIYLnaFQk2uz4DAKDTCEbbhkyP0Q5oZPgf3RRI=
  template:
    metadata:
      name: netbox-postgres-auth
      namespace: apps
    type: Opaque
