---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-oidc-config
  namespace: apps
spec:
  encryptedData:
    oidc.yaml: AgB/S9Yfy3BIsLRy89NtbgdCqUWFeznOKJlQho2Vqj4bgPdlfj81Da7M4oREX5IDqLQHZtqILBCf05LRPTH0SIcOraRtOmYYHKMKyEU5LE+KpthUJ/lqtENiDoPADILPUKEHwE7sq2lDHmA6WvM7mrLfNIm1XZ6SEvqCaM7Fwz+n9AWdcpAVzid54pXG3D/ExOL0JfqFOT0ulSBNCLo0qVcSbQ3xFabOnvrTR/ehVup58TEyOugqyPsL29GcwoJwsLQ8N/UbTZiR2WAU8MsyqPGVpRADqquKCF7TpGJj9EgRcHMH0azrmq1QdoTDMaM6QVl8BvNnZcthVWb/OLic1octVJPjm0jBOQADcJsQUzLBE0meovAX4+A/M71Y5yUXthcpApJPzuM/MZn+HVRhfYOqkYrWk2Z//kK8pg0ZnEp3HOV8Y6OV3bZLDuf1PcUR1Nr+8+FVD4I9wqMitKXjMy6w4F/m1+ODWgeamc8vBVWE9oBddHlIBlpoGmyj40H638ZVtukmktb3gbMXO877EpiFMxUJ/S74wJBhCRIPF6Lq0wFCgQJFNto7zrlxACpohWH3Un/W9ZRh5PKZBEIZGKmCKv6cvUHxlz+WEensptSKf1DeoCfFdSeVMbfLEjGhs53BXkRL3lZSlgzDAYgiwTRdaSKaEnWbE8EHsSAzc1Y3UhuB/coRneVUN0nsNJC97+f29PeWw0vU35OvqEpUX/RU2K6xRA+oM8hwUsowzlheDsZp7EgRXbH2/XpTrtn2Fo7WLPVtJ1asxwSw2YcYrPucy+ixtGXCGUrHYyVVxUz9Hp6SEP3O2M8VBjLeqkqs3KGedCRUfklsLCYlP/zFMeOWaTuXa8JgIDMJmIm5KoPuNKXtZaSfUQ+pE/K0p3fP4AywCMOPaYusWP9eQTXJwJ3cK5kOYf8pui39n1mdkREn78Y/VlLdA1zssBiYteLJwSrMGgGgqf0Xh2DD0wqfEnL0ab5yjxVIKH0+Sg4XKitvNWvwKifZBIQfrN1IewVNy/t8F4DQbziNX0WWZDPN1xxuFOey2mCoMoGsRbibV+KtaPukABc6/Rnqn2l6yJA3Uduw6RQLL4sW64syJoDHkqXGjq4BQBbt
  template:
    metadata:
      name: netbox-oidc-config
      namespace: apps
