---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-garage-s3
  namespace: apps
spec:
  encryptedData:
    s3_access: AgALFG+uDej8nZB1CNtMtcbAZZNVI028zt+VXXXQ8nrMQ47aUfTeWkQVsVYw+itO0Mu26hsA2phnljJOeqDSqi8B49nUdSFV8aoUh8TAAkJpmarSWJsrVONhiaL7d4TICvXT2duLP0qwfml6DfbW6JrH0AuCweRXz7JOMmxzB0RnNxk8imRLI3Gue1wlO9/zEk9q23Vz6qaAgR7ZITHkY8zDA4g2Isg4sg6VHAhMAWPbaEGj69N2aWkNd5krkBg6NppFKrig+qarZJMyDs/epk83gBnD81jjc2zimAzM+Xb8pusOeMcvR/P2NEJ/VlmEe8VVGiBLanOBJRL239R3KZqXLrI3x+R+xc0utfJmZ6JJ/3d8ELAozAF7vrQtyV3nHuCziJFTUJ+X+bjIrPDI95Veq6vUFdPq8UhWpSNDIjUgd996pxT2yztgxbvo27T9zxFF8Gaf1fkK9V8lcJ3xm/AwFSMG46a134krv56c3tE32nMBF3GQ90KzjQPbQNS1bw5FgN+CBzZjgCqnlytVNhGSdHG94hgAHn8xkgqtyYBnN8nC1A7Qc8T7Dib+vaZgsy9aGY1hrOTiIT+S4kSpaeaDnklbwVFmhJ58mKrq+2SKvn9x5r8mnzy10AedLAV0qhziPk3esdsp/qwwh8S7wCKgdJsnF0kpntsl8Ap8XXD2lT5B+94BKHs2D1MTl+W731OTAeQ4m6Ftz/oN/Kol+FJSuP9dkimpyHdWcg==
    s3_secret: AgA1ifz+OZtjC11xYhLhaeMeOHXglLpij1ioxFA+JJzKxYArgjY0dO+cossYWCzvnRO6ppO5BvKjRqJFnK/zQUTu+dRt8o9XopiVr0iZas+KPpekhs57VG3EI9ibpAhfSyTdOqPPjIHAGpoDO0jXMZnIwTsGwDcsfvW8wcN3JBDt8mSYrd2uBMqk8Gq17MWp+RMoiPk2s1nX0YPogqTXLksQSwZKSEzb8xyFLkTVFgMmxkJb7zku8OY1d7YAHhCcLW+CY/dG3XQTrCcT2u4Fjb6qLH8Ekh4l8dB45NjJJ6p0eYJ78y88OmtsI9ax6Cbu01MFEo+xRT08nbxIf1ztWAT+0ojNlHpJ5+2Re7Q1lxVKrtKiNk1IsSFV5NVKUmlkcuDsD6LcXiHO1oTNSb7sgxueVcxkabuBCBHJkGEmy+Eto9bQRerT0pwf/862bdAGQJixtUn0AJtrQppGgrug+0OJS0nmnA56HH4F780WhiEI4gKouQrbRjdyqJn2Mohw/pnLaSw3WBt+ogFEbUD8cqH0fis05yn0i7s0l3Ng/KTiPPUzIs7WTjhjjngl94AMPeDbQXDwS8BieX7XQ+uLHDHTUeaL/zA/mNoQRkOFbcPJqq5Eo3lwlWeizME42W9hbj/i6jG3eczh6p13aBQOxT5mjcheq1Fo9BdnTqTVEJabQx6rQDILnEAFg4DgIA1OJc07OxoilsNLpEDFNHiRW9W+laFgBe0l9mQdAraJ2guMSDZbSomPxRSOz4ryk2fwSaZZq3awphd0u0MvRPUHzPka
  template:
    metadata:
      name: netbox-garage-s3
      namespace: apps
