---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-extra-config
  namespace: apps
spec:
  encryptedData:
    storages.yaml: AgCd5GJKG9m1+1R7RXmaGz7aIb/ZxJl7nyhVDw7OW4jhfzLsRCFc5ncvx4gKxM1rmh3STDU3XpqRpJUhWxiE+rGcFQsG2fg8T8tBGeMJLP9YBR2kRnPIWIhaq9gg3uKz7VQZ53SEFd4PoXKTdeJpnpJq6AyawBl4Fdqzi1sLCbxusBwHiflJLM1vSRgKeXly92rCplTSP2T1Jg2HJ0DCZgoCy6mFylA3SLyDru+DKavxsZSGeT7MZxdGRZMzE13T4VMygpJ3+n1y0PFWZU6M7t43fpKSqfztxZd8+hEU9Dvyr+4fQLK1d+37ABY2GacewMLsAeAJlLu9+3MPKUEp5yt1ggzMGwVmcZezdpHxpzA9u61lSDUNykzqO/5J5h6TahyIpFq+EhM7pJg1OhAq5JWfMkQlVJs+1zrqpbZVJtlpIXAytfZXNW2OoJamoFfr1q+XgxjdvLN0rLONF3pf0srF+UIHJVSTSxtCx9MYmDOc7HKNKaDsRyGM81fFvhJWsW1K12riT3lfrfb/0oIb64Y0sFFfzoiYCzyPbTVeziObmazeaZOqraRi/dgehdWI/OBkK3J0TTGjjjtvE2Ba71+wTatzxE5eczwanloCnw95hKaaMXH2ufv1upaWuxYaChS5lCqgfRoFHtpYAsC5TnhA0BBlZw/hGKbCzqG8IJn4wrUo6MpjyWNpDkUiZLcPD77Oc40wBzbfm+mU16I+PWBF4f7HNQFLNcQBgiBIQqC9eaQaHU7zhQidT+o0OZDEG+oL4rtcFCl2rk1f2dlnwKHQGiiWlzrBC8RUR+F4249VgHIrl+zjiOGc5t2lphu9aISTbyV2HGAg/WScR/UO01ANQRZ9jYPBbmZBkP5vWsikxvsjugSGHm6db+NKEhNsF+/nXv3nWFd07Iv6+pEsOWK7slJFYBkhQVGFPCwgECaQk3pVPNNSCAotClWG0I/xDDcVbix/yc8XuXntwKTo6Po4olTMVP2LFwW1auIIpjMJ3PR7I3LrTSAb7ek9YG+sTPT4DhVQ4smdj688bW8j57g6O6d286Mus/6R1vWAv5X/xvOsZvshNSbQvSlSV18Lp5Gl/gDABBvTgf9xng2KNSWXb6Klp1ZtIWpduBKN7asNgjq1NoYdBAr9
  template:
    metadata:
      name: netbox-extra-config
      namespace: apps
