---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-operator-token
  namespace: apps
spec:
  encryptedData:
    api_token: AgA1A6vr7ZC7rzo0/jd80FekqNtQwwRCAQG2smyaGsr2xA5+46HIyw7n6KVEZrDrKgaLBo/l96+5D4FHbYIG+YoPY/H9VtKehx8qp/XxWplL3uMgaNnPQAGbPeiGkTIptf3DVugtSSIlpRpvC3l2HJIupCIMLEPQsO60Q5ML0xE6yLEIRtJLFbQlGTjMgmn32VYcpkwvJJZbOSWbuD6zyXFD8hhYE1V4d1jRa635T+Pug6Cs5E6huzCdVFSmZu1GlMVw/vy3v1gmBZXFXTn+4e9Lyau/StZMNIS6wSGt8VGEv3tpdwTcZqh0aV7ruCI258d9zw0n8Nb09Frvluowh4VCTZ0vvNJOGRu3IBm0JpREsE0URaGJHg6XslurwHWXPRJZsgO4ssIhsVJ4qzcEeztnaoZcvnjqc3rRzH2GbpbFpWufmdo0XwIPBxMGC9EPM/juvvslwJ009Lkq8VM9NAtwrMACEajEEvA9U7t2wUtmiYinJQNGuA14z5SavZl3WXv8x+Ye6qdQTiJUu/7iUfvTsEk1tvv2spXpFYtBfz+pfiyHBlUbIrGUnjsGIq4vSxUHT7ejf8pSLTExJkTuZyroXVsIxCww6yMOkoRkudC797yVFbKIFyxVz8trD+awRYbA2n0CwqrwLm07X1mNYqZDDpEDwCvUtQAOeabzJIeaVKsO95F/1QKBE/h0vnYKUs1Cr6QsV5QBTS/fDEUGJHC5+hZdKc0Yskxze1PjhMrzfdT5NzfTtFUt
  template:
    metadata:
      name: netbox-operator-token
      namespace: apps
