---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-oidc
  namespace: apps
spec:
  encryptedData:
    client_id: AgAkUYGgVguqzFGhYEzzpvVQgiRT+cHfZzE+jVIvwiRDUkSBEBwklSBXhaQPDNCiC0kOKu5H2hu9SwNBVK/1VBScWxIE9B9Ida76fNSwUaZ9/hmBz76dvlj6D9zGncEbjaoxfI/zh4Yq0t5fGXkBL2twzIk489g9kM89YrHeUoMBcSoc1yCroXEz1nDWsbevDp+3f25S17ryQJ7x++L/hMBRy5supWklyT47QgD8XlEZMs46NxhdCI79ZJf5urF6j5JEI5sWotTNjzymtqrzaPdrN8huXXmYukrv4RIU/4bDgZ67x6WtRk5O+EqyNyC/SNxAysPQVjE8M49lr4oRAX9j05yNtDz0TbzsOrDO0dNGNlGpxOjcxWKONMcwLNuVx8IusQgjKvuNipps3By0J/5TJ34zjH1911Cobhed6HbqqYlZ8WWRJIBNvzDYxs5Se4PfTmUKwyQt+++IZp/n6GRLwQGMmB9MVr22+9uonDdnC2meCAA5r2uLL/Obs9kkUpIPs5L0W0r9D2CYKyknFjfoOVWfBd7YxTdWnfC59JX5Cohivnf261zGJlefRzIcL6TRtsNWm7LTKWv8zUbEfLH140/xw8f2cjMGdnzPCehKXeLrrwWetlvVuCsD8xJ3QSbWQDzUNTHSQLAZbT8l44EW/5mPZLYfHAkRP5k0PvEVfBi+UTeDZHUTRzilmZaYFexGsp/b44NAepZ2rIHQV3x0kiFEhLarYwc8+rBSyl/3fZabmmU=
    client_secret: AgBZ4JU9yw1Euvmja1C1SNpcwP5Ko/B+tNGlaRW/rvRgIHR0UvKzC346WBR7q8VriWpqiS+fuZkrEPcXC+GAg6d4f4Ar/oEW4oarZyE0HLBr7cOY7MfFDB1VOjcsMrPZapFa+JzkH3U/lzsTdMAR5GSM3cl/C4xyPnP7wgiHzeq/OVfWeP0FllnpjUJQhqhkzDSzQhKaJ9ZlNzE/Cc7gwMp9CW6RHaO+8E2M2JnJ7HGXEI9d//KuJ8Zr3rh20teJ5AWd1E93xzcy91j6aIhdV3SLENe9On0jjmJvyPiAeTuGxNM4qakHwqVah0eBtdNvigLBB/N2AVTQFOtN1rvq0UVgbYvBFTZWvYBLi3Q09yyq3jXu5Va+cReXiH9gt8Ps69FmzlatVV84NU10wr+oCCQNlgp2ffMs58mGnkjhf7B5hyzTbqz1QrOp2mtTDjuIerJYG1ZcuF3XP+Oe3AMYXmewLTZ8h6WCXtmbR85f9/Z/SteG9JWWY/gSQ7tOfvSLoOmRD36oeWBzrML6egmvE6ySls1h/pHbmVlOOkUieT8X/dD5nHgcqHMHyhwMAnAPuajKYRnpepbxehwNaQyEvyhG/bmxV0HChVlg6VPXNTsEo0MCebsaRAAmEqQfXsDXV601bOy/ofqxdFp7M7rCLa72mliylGO0OTFA1uFYUoolfBMO2WnMc1qxagsqXDapQN7rZLwLG5WBC1ENN+FrCi46DICKbOJRts/M2nQKuUcWi6kUf/Mlf9LgKr1tmz59EFndKH2HDrD7PdYm4J9kAXgY
  template:
    metadata:
      name: netbox-oidc
      namespace: apps
