---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-diode-client
  namespace: apps
spec:
  encryptedData:
    netbox_to_diode: AgAVsO3U04FVsx/fvY9BO0P6dVoSUsHbYDCDEVTE+BMOwAbRp6D6rCvDbcz2HjOR9yIS4a/RyjYvvnfl2VDi3c6q9+LFqxXyPnTEt9FSYJPGwywpuyX0KTURj2o4eVE/TQVz6Uxi+0kqgWie86m9UwGmzcF/DQlY/5SotYfgB3SIxs5Rjjl4vhMm0w4RlsnDJqBLDftMJAonulQGP0gXhioID0qG64E97WDP+gIuVJRVBEOWzQQWrjkRfBpDThM2x8MChGx4c2OYFe1zoM27XFmIO1vkm88du2EciMyQTKMHJRCJjJ5KT6Yrn8Cea/JLCpee0NegU+FSsyWDW16uLvBnQ2LRDPOAlZ4R289G0E1kBDKTvqUdNjKctSDxspy+LaX/ErlcBiAbb6bRDPe1/HUhN6WmT+/kC3KfyAbWfRZCOD3ImJvVs/dWLRRmowSzdZZuotbAcJkfumT0vMkX100OdyAnCoVgP6Kun8H17sUf/d4Gn0bpm0V2/7nIrEl3x9ojPWOS2kyD7mWodF1TK/k7R7iwdOx69lD0a5gpwIeVYjh7DVNjP4k7WcrT8IjdCfdoeU9tAj0aoSWRe/8YVReUSLltSC1fzeBG5/VCC+vb8Zyp4I2BIimJLVt7HexiNDo2q6Vz6SH2s5EkCvcteDL1qsU1/qp1JP6s3osGOgKUTY1SZvCMVNerVEFGGArhsmsxhcQ+HKCIb/mbPtA1iB7Ei34vJsjVxHLQnQD8B39qPg==
  template:
    metadata:
      name: netbox-diode-client
      namespace: apps
