---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-api-peppers
  namespace: apps
spec:
  encryptedData:
    api_token_peppers.yaml: AgAOqjPb9alWIHlAQZoV10tJFyuzcNclxPcJ4Ta2hoaezRLrEq6srUF9dR1rWKv1keBrY8ADm2omiDIjSL0mTbaOQy49i90Ct71oUNhYBUdaFc4esh9TNoSxd/fCfYNHVRlJj5dJJku24ntwr9olfG129h+KEyTMSmhFookiQpQUoSzAWzZXvOPbFfQHR1Pdc9cKvZTTh0bFXjI3PuGDFnPaHuucBqSWMfsSsafvkf7qXGjUg8JacYT54OLCfIDX3rsDT3hVvQ0zJNNQbr9u7lBE1A51vhFxqzgtJr/CVQEy2iLtmye1y29rLAYzNpitrfZoEDoLmZ9Y/rJ0QiItVSgxV1yk2Z2nN05xVP0ko207Nk0RWJIlRhLy9fX+kJoEVtAzvrTWNol8lsa8fLb8NMN09ufyVWw6yBx1UQKxBkn3yqqa/KAtkyzoTHLDV39U+36h8P/JazOYnXZtYXQ0TOWsrAnkQZCKNwXCPg3oMk9erxG1aPpIXf4Z0FGU9uFTFaj/2AJBrgkHSCAcyNOza2t1t9Etb3PG7i1XhjXaZiatYNtzkFEKojVDK5IQNMa0IcydHhjuOMpH1XN55BOtYAVSE/Rc5tHA5fn8O6k3oI/1jF74FA4YrNnFlCupgU0F2pQqhvmbQBFZUKlho4XkeRE/HE9ZfjpyzIECYhOlbH1PgRpvvmGs4iritKMpWQ6DeWqh7EU8ksjQ1ynHbCCqMoqgoYenmt6/uETMCCnuy526/fm94izcRyJyi45vOMjHQOBo1PlqivdlptgxJFlZDLNSMDVQfnkO41v7ARzGRu+l+silyfu+Yl4=
  template:
    metadata:
      name: netbox-api-peppers
      namespace: apps
