---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-operator-token
  namespace: apps
spec:
  encryptedData:
    api_token: AgAbgcCS/+yskanHlT3bW4K/cldX7t/x2irZoeAmHMM4phfRurM/3DD6/OfBCaXyubSFpSUihauT2o0kqRUKIt01GbqTQLEbzSbviVGB0oHlmrQmTsFsWyHkJHLMDfvZViUyg+NwMiyzZ/7MuwPQOB2tgbPEtBGUS8K6tiYtO3EXtDgapcrbDzlAGhsbebOCfvd8RtzkOSF5A+fhEYM7s8cx8ZaRMxmIP2DgfR+YjO8AHcrRytEPzHIrGi5C4fT9Z+F0RDehHMmF6337jYTO7lkc5ZJA5KlEdAKt2u602XVOLGDVbrxEHi1qlE10sZmZlwDLrY2Aw2T8XycDlcULYIkdhMBa+5o1kUzX+NiG5sOt3mqCGvCZu+zmCF8oOsWfIKaCrhQgHlHRg82pzhbfCF0X8czHiqww7AyHENZIbf0s4i1I3jncZGiLyz/NZCZqcvXl97dFuSwmQQKs1Bxz94g4LZ2EVVghp3fZiBuisretgPUqfyVKCaGaIAD2gLqm+M+T7AF5qaludX4RimjdAQuuapSL21sl+6FFqPFXnqWs5mUuNZR7poSlF8CgSbdVOrldAvpekPSe8bLDLuV4rlDhdr9+N43zbqbtNBK8uWH78AlnRg1lFWTavVDmU5nWDrfEm/wJE96uHUUawP4l3uayR9xnVkuD2TLRDaO0kjRjoXppWgU2lrHdYNxhkgwdYUn54Kn7fgY4jL9HgH2hh+lHXgIVQXObfDurdpl4F3l9FQ4CdMyMo5jD
  template:
    metadata:
      name: netbox-operator-token
      namespace: apps
