---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-operator-token
  namespace: apps
spec:
  encryptedData:
    api_token: AgBc+Jj5+oBczTln7QTnkgmzoK453erVMUueo+T/7f7FhObHHXxfMgHCBHKcHHypR3XN5dFBMr775HKZ9hAUSWcx0+6OHi0bXt7SZcZo2fNQn1K+bL311ZRCDLP45ydo/0m+cG8HSNlDOiRcq4dTJdTtPaZv18dIKjjyMNLdpFZA6NPyRtRPrxhlb8469VczSwdd4P7c1VawuPfKDhzhJgXgq9SrUkDbkMX5K1Ja5tAew2Hwqjj0jVa+TfWyxzeX3Bs0vGon0E/PCIW81lm+HQ8ccxATvjnpjQpS6G5fScqaMJaPFykJkWb/VdZv44raG2LAblthm5nGka1i7MmCbnJoRhj1ehEU9etxhR3sTE1ZDvNoHwoZHFQExtNmrFCUEomBzMqI8bD56Ed4IGQV/qZ8TTiRGXU/IxQIlwPwuhZTP6sFNyeyfvUdmdclWTijn6iaw4esDqTq92eCQSwA7gV6HHSQWDlAzP9svkr+TlFDuI6oP6M4Z8CW4R6XaiZEOxBC7Y5JKwLUDSiGhRKRU6+OZfYlPQeBbvoKnUiUHhReMbEIiIl++0x3aodl//vrE/0yIOgQAV5P/BmuCifccHHRquqfrpu7UP7zyOxzCdSUvW2FlEgt9+BQB11PV+ItvkI442Jt271xXXRUyoGPZQLLvUeaR5dhd5acQSnLiTcbimHVVw2Fm022ncIpRU/0KEw2kFRJkvHiq1HkR7/S6MotJqPAj+mDIQkuzYwwMZOvOsHCSiissKuDQPOriQ==
  template:
    metadata:
      name: netbox-operator-token
      namespace: apps
