apiVersion: v2
name: csi-s3
description: S3-backed CSI driver for RWX persistent volumes via GeeseFS FUSE
version: 0.2.0
appVersion: "0.43.4"
type: application
icon: https://raw.githubusercontent.com/yandex-cloud/k8s-csi-s3/master/docs/csi-s3.png
dependencies:
  - name: csi-s3
    version: 0.43.4
    repository: https://yandex-cloud.github.io/k8s-csi-s3/charts
