apiVersion: v2
name: csi-s3
description: S3-backed CSI driver for RWX persistent volumes via GeeseFS FUSE
version: 0.1.0
appVersion: "0.35.3"
type: application
icon: https://raw.githubusercontent.com/ctrox/csi-s3/master/docs/csi-s3.png
dependencies:
  - name: csi-s3
    version: 0.35.3
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
