---
- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
  become: true
  when: not ansible_check_mode

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
