apiVersion: v2
name: ollama
description: Wrapper chart for Ollama LLM inference server (CPU-only)
type: application
version: 0.1.10
appVersion: "0.17.7"
icon: https://ollama.com/public/ollama.png
sources:
- https://github.com/ollama/ollama
- https://github.com/otwld/ollama-helm
dependencies:
- name: ollama
  version: 1.50.0
  repository: https://helm.otwld.com/
