apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-webui-authentik-outpost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-webui
    app.kubernetes.io/component: auth
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/ignore: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: wildcard-m0sh1-cc
