apiVersion: v2
name: garage-operator
description: Wrapper chart for Garage Operator (S3-compatible object storage)
type: application
version: 0.1.2
appVersion: "0.0.39"
icon: https://garagehq.deuxfleurs.fr/images/garage-logo.svg

dependencies:
  - name: garage-operator
    version: 0.0.41
    repository: oci://ghcr.io/rajsinghtech/charts
