---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headlamp.serviceAccount.name }}-token
  annotations:
    kubernetes.io/service-account.name: {{ .Values.headlamp.serviceAccount.name }}
type: kubernetes.io/service-account-token
