---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    api-key: AgA4/Yv4POy11uzuphE824T8whBXaJE9cl2stP1G9El0EXpkO4MD4emJX8VNjPMvynF9n0+AihtINfZnAnN1MF8c3TwmtYVh+1TStanE0P32RN6VcaSxHUMz6Ywe3j5jvd33N77ye48S0U3I0ovVUL4BftbG9yRGi9Jf8+LSeOg8SQnE6NB28OB9D2rTotV2TbWhfvMd+Kf80QN7BiOztFvZEFy5mPzhJzwXUdvvg9k1yta0jtPAty9shnQF1x1pwyLgtsd2q07FVEauMYCjoe0JBsumtAUTWXwZMl5XfS8jb4N3t36QVH7EXMrEILkk5qIgsBvJoEgD6WWieZ7DOo0cpiPrfdYJ7oh2qUvNde5oV6hAtWUdoz/Orcoeo/tnJe8h14zYQQWxvhxWVr07IBbDksO7lWiXZLW/TRJ6GcyL7B8B2UaHcrZ+MWlRQEvbVmf36C7Kkf3b5PtBs4aGD3Liv9HOXrCJaeuiORlkZX0TYfY0aHY7j12vLfmV8yuDG81+PTDEgGpsV+d1oUYFSVjm5I4WGVFoxnKbSJfUVYNUUJOVVcd/rm45rt33m28tM5OiD/XCobGYdCNIHTb9cuiWHXhQdaWWjM58JpIwHK61fpL2IuYTRSTliNYueTIIJjpmHvt8qNQkGtDprPvNE5SHd7C+s134GeSPHbjJlYx+GGeHbMRd88NiGArJztcL2ZsauEZOEuoGu8MIo/RplTQPMa+gEuiTMik1/Lm5D76DU5Ogm40JdXwHaAu1719euLwB88uafpFsEKWdtdPJjBBg
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: crowdsec
