---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    api-key: AgCGNyohqqEgLzkdGf5IrmQJzKWkHOqs/m7hWYPN5r1xq7u7RB2JP6WS6sEO9py+ZJKWQRl8PDYvwp2J5IDlpNFpMsaqAE/yOZhgEL8Kbk9KtDwQpR4fEogZbjs3YT8bP83FY3nWu7kJZ8xENeerjCQRdxeJSN82OlttTraNroh0lWG81fy4zkWgH8dan9AE4ZLyqN2G1XBpaTQA62V7nZHfvPwkC5Vd+3gkgMiCMUGRxzZBXsPykUz8CDO6sAbqcLxjreUxdOBS9SOX9FRjP1rraUc/pvlR4VzS/zzS8bT1WjOnpihJ/0DwmTFvIVK8nY/GwbJR3X/Yo8HfM0ya3RbXobTMEEinmI2uFSk+h0q0E5k2FJqVIA3ZDsFNghi3TQUY4mxjs+esPyudLb/vdo4fiG50jkNey382A/Tlzy9AcgRZChkkzUIeH57gba0Xxqcj2fgzT8/FKTeDJtddwaAdKDuZvIjouQif4MxrDHAVHzGasGCf6xqHyN2LVBtScOual//z4fTjVYyJMMkS9U3aCaJrx4F0FwOKp3YBhxOZL9eEOMtL49A7N9lnymGeF50QjbmOzPvwN4k3ZvJoTO3VTq+EsdTB859Cs261LlHX58QLgW4GludynTpyhcGXiXw4d6fMi8OP/qgVhNZBTL+ce+ttFg4sPr0Nm5JHeP0IQJ2xv4q0X/i4CDDpSkvfG7Q=
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: crowdsec
