---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-enroll-key
  namespace: crowdsec
spec:
  encryptedData:
    enroll-key: AgCBSg4PKzSaBRRFyc9cYPuW/pO/L/D5ZxBBvymgV5/beUSdYoPY9+dsXXVw9+bqNo4+qmNUCilX+RDa+XsXHUof0o0SZPkI1nE1r4uBoqVuxwXZMYSIyUid/5qUY/3nshPLN2Ie6Wp8OhOfZhgZ+lyBW/6ahTVCe6aOWdEmfH6GwMVgw0qvYsO1PNOV9v/APjxHzdAjkqLhEO52TTll018d+RNH+ZQ8G6o01DAI+laRf7kqPQYHPrcttL2u9QlEKe/UhMD2PNz5tWRPnpRWGcW/JmLhifqR904tIz768Uu3QHzzxUHmPxP3dS7OaivmFYT1rbHlD/kHf2XGyORXOKu5HqU8BF5xODN9IMNmrSXadGa6YZrRcJiKHDFls0QUelWpHlRgPFCjDY99gOzZKVjA+oRHnTPf0p+0fTqlY70LWTWUzXR3e34vAg2p21NCkEdcnMF+LrQ+a7YmeKidGVTKU6dxDpXy2C0lsKNIKuSNJZSdaUDYSaM1Qwq8BxpmdD2H2jg3vD3Q0HVJnKGrF7z5ztO666FRm87lU20K24lhgaCBu1wCshNsFMyjRE4PFXsCX4TiauJkBGP6h5QtxX49BcOJ5+CLoJ8ijhNW9zHhJOS3H4Rsq2IGlE+oLgoJcTWyQHZ2L/JoeEea8Pr9rMyRePUxGyDAGSlo8fSWaYOX4ChMsZ9JHq+kduCS9Z4BzQU=
  template:
    metadata:
      name: crowdsec-enroll-key
      namespace: crowdsec
