---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    api-key: AgBIPy9GcLlgzZtO0558Q6SyfZNG9zh/8nFRHNwAoechmc1+pK0HY/xEf36s1n1gqiJNupKDn6Fbd0ewfc8puJWheGTv7ECDB+rnj38BA5FbrywByhQwWTPc3vOuK66YpQFsGrENKuIdAutqBR1kWTOPVo+LMFVK4VeIZefTy9QolKYBbquOCY+qDU5fpUsGGPhNT90hdT83gEGCUvUZUDRrpuUEfJXUNdstKhnv4zSc+SCUrxi3yyEkUF+dS0hOcNcDJcws+Zp6HZFDrUab7gvXFeUrPEHkjHx85SH98iqH9C9vMzCqEOP1tUfKSwsUBwvjiDHxlopa7Zh15h1J/JwSk3d9CEa/uEUHqoh50VCT41vyF9tqz3kkoXQsf85f7+3WNdM6qnZSn7Dh0a0LK43NLK2gMFxQHu6zJYf4C7dC4Sd4ML+WiF4lXxaxxFKPdfsV0I6/NKURvd7Apk8YatLQYd4oMDtUylBCcaghwJQv+AnbG1Aza550qkBYXGiOEY9i3/jFmVeoQAtjOZr+DHgK0myewBMN+Di9CPmFK7bEInKv6/pFxLnz0Qip6vwkPnaz2m3NpYuhgbfrXOmxzYnkvc4MeYiO24rp9WPWRhUDzasZXYWdhCt1ZfM63Q6RM/JXD4CYCD4CfNafxA5SYjgzl8amLGFOexQQBkRCBGYPthqlDTbvz7iveQHU5ts9WGY=
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: crowdsec
