apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxmenux.fullname" . }}-haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxmenux.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 2048

    defaults
      log global
      mode http
      option httplog
      timeout connect 5s
      timeout client  60s
      timeout server  60s

    frontend fe_http
      bind :8080
{{- range .Values.backend.nodes }}
      acl is_{{ .name }} path /{{ .name }} /{{ .name }}/
      http-request redirect location / set-cookie PVENODE={{ .name }} if is_{{ .name }}
{{- end }}
      default_backend be_pve

    backend be_pve
      balance roundrobin
      cookie PVENODE insert indirect nocache
{{- range .Values.backend.nodes }}
      server {{ .name }} {{ .ip }}:{{ $.Values.backend.port }} check cookie {{ .name }}
{{- end }}
