---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-auth
  namespace: apps
spec:
  encryptedData:
    password: AgCKruV0e484Ne8sTSBgThnbvnocGinG9k+2ZgjKSoijqfi/3Cslt5jCOvf+gCa+Lis5oVReEyTF1rdoglYsO5UuDscuvR1qi6n6Ex0OEstSZLms3/oI8J1bJnPMOBvY84LDn7YJ+5DlXjUXiOdPJKCGuwvFiFDPsspQTppS2hDf9V6m2gmv51HY2NEvXEiWqU9DwUxz0a4XW16kbeYSsrKgujUBUa00jGy8SGcouh27ukvtSbbJqzYgnzfWLT1AshYapF9Gj+jmhzTaCoLKyKFsHIYnyyJ9HCkCfjwtoYVseiwLweOQhuKG698PnMiA790CepIcN9XOsSyjlhmDlXYT+rl8Tc8mhKUEKCMJkEaADNmXERgR9njfxGRY8h66ZhjosV2NVMrXoO03GVaG0D5QTF+3B2yOoKskVXPWroFfzZUAMfs0/QIEqph6ePL7ZoCEHAVWhBvkVUzQ/60lcRuDDd9kg6ILxorrvo5u27rpXixsFWFgZlfh+uaiGx+MEQPCZ4mASkqw+ETygrGtPqySCrinUjo14jPNQr8AfkeMOWkzKTGLSlpsuDOyAgLKWLBbHPwE+wq+3frtgnVxcwmyHMqcGB2AOFYXvE3IePM5sqjZg/ny6wMaftEnD3crwv5v8//vNcf3muaKmL8J+pkl6mEPhgwB657riEkbsrEkIhDhanQGOJYiaaQqsXl+iz3pDTPuuYZ96OTV/e6XNan+aVCg6k/moY0GhdlOyWCSZaVCptTfyIRxHizVYM85Y4otq1V4yWnBSDEX7Xp9Or6d
    username: AgCklOxUbrvyrKhii51FuijkheHJjeGTOfbWdZ8SmULzaYJtyY17r9XlP4+Pd3/Zsrk3HkAlojfHQvdyAVevnr41ArDZl7hcCZRbOHLGAKq66qWj7IBUDrqECqQLOQYx9bJI5p/HCjEf3VUvIiLISX9+RrHW+AmKT/8SlfQyHHx3DBiaVRq8HXXkjOpP0mNUEqqzfgYUpUeEDNDz/hNUZyfvEDSpavwSrGgTp2gQW+lFBHHSTkTEhFsl6t4/cguPxfxCBINoPUuGu8TUwcs8NMiZJWf1Qxa1FwIAbPVmhmkSxb1ExwIv2nzn6cW/9L66umTX/dU+fe0a92wThtrAkcZpe7M5fIuCVmWYanyl9To535Czzf5p6cq99Trsb7cO4F2K8RytEySeq72vO0iBI9uYGWoCJhjs7PqXPb5GpF4+JdcEKk0dXOFEKYfps42O+m0P+Mk0j7jgD5hV3Vw/xF2O0x7rOVvYtVBsOra9LVOoKVGrCgTxq/ueDAZTOFZsdocwrgVKGvXFMTadJSTOq7rQj2pALiYTAJtpvZtVnkgt1Nj4ocIPbnTfqW2QGroVeUydr2u9WuZNLsMVjlK+WUT3m93T0+VpmanuL2Qo+m5F1a3uSbN2yJlsyCzspmS1f4jMZSbo6+CDjW2GOP56FhDZBkJOjIcM1eAnKLK1PbJeVBe0VzFHrva/nIKlfw533irNAqouVgWV9NM=
  template:
    metadata:
      name: authentik-postgres-auth
      namespace: apps
    type: Opaque
