---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-garage-s3
  namespace: apps
spec:
  encryptedData:
    s3_access: AgBg9Mc5hn5kqNYcZywDrjhMmTUbavBSU9iOqkGA7og5nKHz3+eNztyqYhhoOVaZmgtGpbj8DSmro13o/TD40YfD9QD0ayRnwsBaTSZg3NS1Vlb7PoiXBQAr0g1kBjqwVcAyLsblJwuNQHUuNKr5PTVgCT/rP/KHTgw6yKWTHfVgKe3/7ofieYeylE5xAFx9QGDtjWMPAB6m3WKq6Vwu1ig4ythEu3VJfDoxfRs+X2ZOYagSPapc6LLGHapVENr4iZdaWQ6T8z0P8OjFqVgbM22L5oMJccZNFnamAY2pYLs3Wy2VOM5SOmqEWu3bNB/Pu5DS3L8Syt6Am4lMZ2bpaeas47hTTx0jjdkzeEtDJc9ylvaqF1+fuPwQvrLB/tgqjF9HpwCNTTNer0zNISyckgWvPAOY6iQAphPSdGfWlHKLTHPuwiwyfQR+kQgier+OWe0WuE092XZqpAv4E1R0coqB3rzcQY88Ki3o9B4cdPX4UDVNxm+qURzQsUah1VtDJ6MeHJPX3qWTVa8DDp07gr8VhjJQystEO14I5w7HPIqyOiLTdhJu/DTDz3mgLbDfi0+3QsL1C+k7ZdG1DibSNSTmuwRUKucG16S0XP8zNxQE8fagC5ea2r3UapzmTs31kkfrEArKEcFqD80phZvG46buCDmjnNC0GMciyKi2dcpwZZhquq4R5KAW2TJEAZbzNSFLpQ3fJESIXOWBugH5bIap7URcnuTp3d0jJw==
    s3_secret: AgBZcy+aKCvjdxnjZyM3V1QUiFcO6o6ehFGS4XjXY20lDfnc6D9IqD0PDkz0wEOrZaSwSvAWEFA8DCqj54FObuWsneuUKUOxVT2GCJoA5d/RHIWgI6XMxCjpIzakSi7J/QsfVmg3eJK/FfAebyb491Gvu1cQ0F4Htx6ZBVh9mkKQNQaXI4GndNruKc/6LmugulmoamwiexzNmuCtRXvDV+q54jQqt68GwD/bcehuWOJvmICREc9PsJDn/ZIGa/K/TPBG9LVuyvGRRRjf56Gwms0jWTFKAsHEb3KyUWkQihF47d7Ld2N8P5xQ0vzP6KmHUm4cNHy3rSwAvxQSC5Lwho6eVMEdF0TDEMit2jnYMHSqBC3BsqLIouft3MJ5fv0h1oCFBjFgigrCcV3QkKfA+g4WbU+P+8l2q5ahOycR+Cztif8/2WFB5uM6H/e6oEu6x6VwrLFJ2r1b4EvawtaYp0ag0sHoTrcJtachNO3p/tHo6yisy/G7OtAUQjNKmzevG88qKyY9+2jv8jE8HXc+zf6k26hdIcufBY+jq4yGEFCM/Gxdb6T73src2dwHpkuANiIN2AlF2Ookhi/pdiLG31MzlI1l61DGNdsIVz2upXpPYiGIr1u6fqh90GqR3UJ2clPcRWek6RkP47AbnJcC14xd5abMHVYtAxQJR4INt0mEo1HiHTxoxesKQMdNRYfg5eeTmh+xuAtrymALD/yhKfgChxNdLYX6qSsI4mR7T6Omh+bl/nMgk4UZOQnpcocUA6tHmdoGKx2/lzhK1m9MFnXM
  template:
    metadata:
      name: authentik-garage-s3
      namespace: apps
