---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netzbremse-ghcr-pull
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgBm2b1FdEML066uijlPk6HLuAuXmfnU+8KQt9gU1qSF75RJU3Rp4NmzA+GesYAQ88HHYlF8OzzOU2WcCqXDPNNZNA4T2YAW1gAHyZC7k8On/6XfK5TOL5EBwJZeydejdfKv46qE+8vwuFNizySKMrvsWLoQ6UwEgmkbrb8j1T6WWnBk4AVxrcB/XSeid5t9ib5m9+z+W5Z9aV9EXeJc9ZQ7mJAh8/lO1XBl0gVk/kX03DTzIPj0eiSnQPpbV0N3Tse48qnoE3DwwKGKs0ic4vcky5hTSCmoUgymh1yL+GWoeJpqTzVwxh4N8e+ta7AQJMBfFCr2CPeQhh1QInpM6gVbCq6wGdqGVB4wt4gJK6fujfo8vipOWCiwK8pRfg8zh2IaMZXACrXmWVT1fXLOkDxwyW20cPBrsUH9cKtt0CPOAhA6/JI+bTKZzH7Pa8mH12iozi/7weujYoTmpjNZ31o55K4cQwEB6r7rl5Yzoceo+cu1dYglGOk0QTRsgkxLwUhQRc1i+1foTpUIQ8R9rgF37/CcWLqVrtUn02CujWXLo0LiihU5K3BPMNELeo1iidlS4wKsTIO0ptlPj6WFLigajmbKz1B44Qyz6cE9cvY2CzgzQrZuH+/kCjry1bREffND6pS1E9Pp5wFIcRaou8EAbubc0iC4uYVSR+lX9uwRhjrbntXoVHX5bt3qhiaXItWM6ugcvKH6K5qCa8KlMuaXX27Kk2XH23KNO+dQw88MjvuAJhjOxw84A5pMzuBDO8Tf8zFHEfv7ljYOZYFR8YiW4RekC2dwC/13yenWz1o259hjxm1XMKltIQGU9awJRME/sCQC9tnWdNa9gskeNeWqHmwb1QNxcs969cSKnSKjTxVXTH7OM0kGyenOdn1wVHJA0GXtYuIsjeAzUIqER7WCmXzCEzMrKRNsgkkdwnuui7g=
  template:
    metadata:
      name: netzbremse-ghcr-pull
      namespace: apps
    type: kubernetes.io/dockerconfigjson
