---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netzbremse-ghcr-pull
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgBh4VE8WRPdyXZNYfilUaipp2+R4Hm59kvglxrsdbI0mlDnP72yAwSufQO6NaSIOnI6Z09qiISzCYPL5xnwZ46LpG/0IBdnZAQ+wHY1ZFhemcnWIWBwKqP/R3OKY27C8uKcYZoDhOMi9C9jxR42b8bZwncq5U3bT71NjR3DqfhPHXKkt97/UhqM88GNRMoxDsl6DCImt0afZ9LK7SU48KEn9PxpRGW4kzAWUB9258uuhvaG0GLPxnqQslnhVPOXzv3VQvR/Cbezd1SoeNP2X41CXOi5bde9/VbH22MseHsXACYjDxQSqG1LcF9giP8zgOpsLdMlId/YZqkVTLxDlJ//jWbsH/5AOu8Gze7ZwUPVtHFpm2t0zhEfl8e831LeA3DBNG4Kt/zKSOHravDjpq6dVoetL5gUnNZzxAJGVQHjIIZuoqPCweGhdxO0cMmQQVqe6O+bydUPLGCiZMmso+ZRhw9AeOca4aPz8Lci3lLpPozX4t75AzA/rKnbFe98l0TLeUTSF6Y0POg6tgO7i/mogf6dKrvRjKTVqlFrshu7ov+RZ01oALynvBWQ4YWk03AXxoF2+7dEjIZzdr9bl/96WbyZuxrh+9xk+tZsn2haqYytr6Te8tmSjZDWYCW728GgJ5nrE9FSYG++8oJeKxpltXAsALLZu5uiHQIGS6umI6iRupMQOOAcLhkG/eQrwSv4tj142Q7mK3S3TQ7Zd3enFF1Q98+t3Am0YyVeN9YqaZ+1EljgkaoAXHlrFWVK7TaBybQHeK/rVqO8k+I1CWUU1ijaiEbf6VRz3qQ9XsI4Paq4D5qOQLBKynlN9S4mhHnA+BSYLucLpDObDusySzJQG8hDYE/6KGBw1uZ/2MgicIokWUdSjBYoKcJix/J2mmt1rXmtzV0SRxMt6y+RoUJh4vJeFQAbBwKXv8oTvAM2sGdGdgxKG593ZYGqnjhtvCVTJVGaFt7p
  template:
    metadata:
      name: netzbremse-ghcr-pull
      namespace: apps
    type: kubernetes.io/dockerconfigjson
