---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netzbremse-ghcr-pull
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgC77ZFUpdhVRtlQDsfs2m1Zj04XTrunEQBgqrEdvWrKNAmqKsZDKnfAfCy9bc/2EjuauZdF5k8PaF4QD7ZLDYDfXx9QGRzMd831eOReRoS8hVOiA/78tgSqzLl8tTBCgC/KPvywc31qbeibIg8f9IiL3gGSCCoGEWQArhbDsh3D6J0hrWwXmJvwUDHlYXKZF527hGQZAW0JIn2WsgB72YUU5QRGiWL87pTQR4FCjNjTKbVm727JVYqb0Er9fS0sIzkUaxLv/BHwAT+6AXXjEdSDg327VsRdecDpX1KFNsVPV7xWwwv914dPk2mYKiOLF0S8RFvWrNCsv8M5OfYnXkgH2Ft5tR395uFbZEoKvwtPrwicNTs+Ks5r87u99Bop6uc57C0SisX51pWL81WubQTHSP2OIgC85VuGAzQNwAqZq6PDDPriNVL1w4iilxjoFi4ReK21saM0k81/RSzkkQTiZfRTieDsImnQSzjbYeQV9QsryTqrr38DUWMElni5p/DNhQGjqQrEjJJfjcUA9R8tdSRjVrT808QTfnR5ZCha6SPu+TGrad66ADcmO5UyAzXZYnQDysEdux/rtk/fnYksycLuJaHjBpNBAr7XIGEXTqv+qchezIHA7sC/DOfkvyXc5Hjf8msEHuYRUGOhZHGuTpXES9vjHnOl72XgJHamJpXrSxDnVnPXxcKfdz1KCdbxRpl+bXWqnkF1H92wPP1WolCsKE5k+4b5V+ksS58cflbQ1sjXh5Ci74ijfPaBPDpHNOOViWN56WtsakugbohviB1ZH7+nZR7oI4+xF1LtYUIdzW3SLXQcEEhLhOYI5hPm8DZLnbPNc9meEzHLl0on/8/1k/VQZc1umn1kLqtJ3ntDQ6DdI6afLE5iYhPJrXROzd13tc4FWpgoStTxxzgBNRLAPqpCiAy0hIelUMVHP+Aa+FdX1q3rOEoacGx9r45A/n/N5yWk
  template:
    metadata:
      name: netzbremse-ghcr-pull
      namespace: apps
    type: kubernetes.io/dockerconfigjson
