apiVersion: v2
name: traefik
description: Wrapper chart to deploy Traefik with pinned DHI dependency
version: 0.3.22
appVersion: 3.6.9
type: application
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
dependencies:
- name: traefik-chart
  alias: traefik
  version: 37.4.0
  repository: oci://dhi.io
