---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: apps
spec:
  encryptedData:
    token: AgAAOegUb1ZSzmxxXGqu4ptdTCRRbGqexD5VRD2wfTLyIMY041Erms7yM/QZNjdV0BOmZ/PWByf/djl+XO47JzVFBYozrtz5KyGOgLDV+RvSouu/SOmbgEYpOZTDtxWgsxoDc9jLNHvLfQ8ZTMyNuioQjeuy5Sah6VdxknPspCQYPW3T3XvjlnFSUn1qt7OnFjf3gBHhbyhHnZbYw848+SLzyMNN/mV1EjOyXsCecwLbN0Q/wikZeU2WYTEjbZSHFDIRMI/sR7/kzqWY5wD/B+6evo6cAFEKzN1nRaXgqcluFPMNnoAF2RpWMixF8bT8LxEiCuJ4z3LCYPLkJm//fJcXj/5zXkqCm1fk1lmiCXwJYXiIEli4sCxb3R8BV992wZsYpukPefMh3SNcEMfp+s5gGujuck+CSmDuMjjW0sDgfSyCcqujSwdnzWAtit1DGsJHO3heiRrixufEG+JRKXLOnYu4p5en5Dp7H3KmMg0R4NFXV9j6DXStxIQipxsXJX60Lw4nHRe31VqMo0u15akS/VHfwh8RM+OBxtKRVelDoG0kRuLF6Y0prPp8Pd0drbqn6DW0erwpfidDIlVt1/wam9I8v/COngwqH4zvOyfxKou6WBdSwfTpP4sL7Ge7SfqYrTnmKmaGVl1oPY8S0+dpfzivhUwdA9XbW+nx67tfIl3KdbVHsWjMqKpvrIDoQZBxoTZSaH4cc5TONbtpHKHqCtc26R1RFYUwo0bpCSZ/lsP96TsdhR/1VeNce1ktapEI+DeGf0yGIuuYqkLfWqgCl2vmKojq0sngSb3dewY5o/WZeQky782GsJ5M2c0ies2bbvjJyLVxXnLy/Up70iouMM/sw/9GnuxTF0/mJk78J0xnYGOeYQ==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: apps
