---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-smtp
  namespace: apps
spec:
  encryptedData:
    SMTP_PASSWORD: AgBGOqBlB7pA70gwYa+5cZLX8i7DGMSLeZv1GBsMd02hceBuT3uZMz3XeOkQk0IHf8jE9ZxnIXS5bw9J9LTNG/QfIno5wQLIAiey8d0AJRU4BrRykXT6tCaHCWtTluhtFFq3V1xQkd/4ClgqbtuR+CWlN007RxZhvtpocxL+H0SB8v3D7H6A99q0p8D5nv7vP2Lr9gkjV3+xrysF68fkPeUwOakwc9318VkUtic4xQ0k0e+p2Jxzn4inLeKuknoYTFL1nHJV8aVQOC/JwYiHKywSaxA219gT5BLCIgkasSlOWG4E7ZowmYoT8U+SNXwnZOLQH4/bHJ4tc4FiLrU6TF9TnH3xi1ZL09fhR3pHjob/+KfJ6AR+73G66FG1sf5fB0GOrphXWNtEdPE7K+3RUP8StRk7Aewf69EY5wOb6NzV2c2xvzorhcH9YpMlGPikKoQBRiLgz+zHCbGsRUjZXmc+GrwCHk6VDu37bT0qt+ySolVS3/qkjbv3KO/tAQXxm3UjvNdhq7jW4XOvDXlttcOv2I2d/8m9nxoyn9O4ye5CLraH0z0AX8/GxpXWPHDo7bbHHU0o1rPYEfXLkm3AaJP0xb1G8Nq7QeMscQ59f7/zb5M6kRrNZDn/nyq/rFhdsOQ9ar54M7av+rJKKqrob40gk9UrO/Jv34tcBBOKq9HMNmV9v945olzAMb4ZxD6ercthMJrvl2J6fLHjWvzDN8RX
    SMTP_USERNAME: AgCWYGaEmdewAot5KbBgDTeIMreBz7mz0Qg7nPIz8VNb0b8S+MNhg/jOcn/18MuyBhwY+TX2bCbh20d+t+t+T3uaLZN9xPCPUr6bgFMEdg/0t0Nk9chcz68qJs0xU6jUTF3Hb8p95cq6tJvIg43No0dLmNDp/0wHiDojC7QqjwSevOr2Yk1nb1wfU5h2kHVbII+BNsTXnF34j+IV83qmktoZ4AkMBl0PbdMvHYWOJOjlNRv4hbRdDr57moYYR5nL87UHjQsc0xWi9qiymjhmH+2WOWNiF0t8y6upvPi9XLdFeyE38Tbz9n4+UTjfaGKxrhp4Bi//ohry+dBkpJFFd1JReUD87UVmISLmMZG+ppi9xw1PPgZKnkD+yOeJ97cTlChpyu3JKcPoLHL7chnBT57Z4R4WDT+v/PVstNQcboIWKz3l3X+8NOcgX7gMuyr2A4+f2EEYfjyEjrHa/cEG1+/YvEjFZmVbKiliEuIZ0/99DBnZfJGUeKQeJxAxfHR1PYct08GGg/tOXPEGK8WZvN04m5tvokwSCdNRmSTUBCL63SDJ9pPQy20IgHE2ezm//2qC3XQ3fJ+96vbYKwpDV/hB8k6/Mliot01T7Uo7WL351z41O+DfUO3OX9tCKPFwAON5/vc7hihsHf2qc66Sv1s5P3s1fnnp1uh5rXOMXi6OXwwdWrn1xq8Ud9ihaj7mpNg/28+8ZNdR471e869BMw==
  template:
    metadata:
      name: vaultwarden-smtp
      namespace: apps
