---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-postgres-auth
  namespace: apps
spec:
  encryptedData:
    password: AgBEfFxV6be+wFscQanM1UkN8dKK0KkYgTaQqjAb0KxF0kXWfCBgJS3n/Mae0EDoak5FrmuBLyS60Yex3GJTFqnl1Cjmo/3uxEmaVB/edKsPVr7OHk6tEem/bUcRNg/44RGRU9z4onc5PnhZI/axtbU30iMgU5Lnvx5zO/ZCMUwcUxRr46AQxPCki6Q+3KGtWUNNq98BoLIDsHXup8K9V9yENLduHXr9Z0vWaLF2xz4vAx0WoubAqoJsZp7o4xe5cAiU1Io1JCoO4x7t72FJlZU1e6riKx4Rjduux8R+AF1WjDMwVCcL/E0dYp2Y2Dee1RlayiE7eJhjWO2J0bPSNML5nMtKK/2EetzBrQMTl5L/EbENO1VIVHb9dFs8QXF/iV3dWorwXcYRPmtVTXv6YJxs6nZa3D/NNv56fO1igu6Z4HBgvw3baAl/GOVr5YqyYNfjthBcN6ziK2PYZb5FkIKTeJJ2cjs4ZeGWhNqZpWg5uph11X448B3X7oKLxPVgjQnS3dcTUhK0C0VoRtb3ljtT70UafYOfXtHYYrogOKHgQ0V2IKZevsiQUbaNI2cCw4agNlwNdZMOaH/q+tMTaY64X61FjVKqCv8eyVPPYWQI0gVeyYnIpcu/+6AhsxKkWgW1ZGfI1PCCtDG2sxP79pIno6mViUgLfVMfekvdRdZAOIxPfTB7hYQfMh6KE8Cmx6BsVQvdPedUEbEzc+JowOmF7R7XkiU3YqI0tIvTr9CcpQ==
  template:
    metadata:
      name: openwebui-postgres-auth
      namespace: apps
