apiVersion: v2
name: renovate-operator
description: Wrapper chart for mogenius renovate-operator (CRD-based Renovate scheduling)
type: application
version: 0.1.11
appVersion: 2.4.2
icon: https://docs.renovatebot.com/assets/images/logo.png
home: https://github.com/mogenius/renovate-operator
keywords:
- renovate
- operator
- dependency
- management
sources:
- https://github.com/mogenius/renovate-operator
dependencies:
- name: renovate-operator
  version: 2.8.5
  repository: oci://ghcr.io/mogenius/helm-charts
