---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-smb-ingest
  namespace: apps
spec:
  encryptedData:
    password: AgCGi212s2ZFp/R8j0rfuiEc811+6IcqvqZ24PE2nLxl6BokYDZq0dt5BPNNIXSlI2eEAj3pKarxwdmOMhffd/gSAnfPdL0JwLDvYKXo8mBVx6KDi5BFPHuqCIzzFwmcAxEDVHKilM6U2+i0gr69cG3IOZHTFiHi45UUmA1KaR7ZfZA2LMYt18gFYQjVuyJFioNC0TVOvLPC7TpqR0RGQuA85X02FBQ+YuLu7UqMUl8VHKYE4mxDF3bh4vlW+ESOWohjPky80ZSNfoubjYbfJqIaKxyq4V2mYORrgkeJCwNa3SRGZqgtIoQqtHapJ3E8ptSNZhzKqt9a9rPGQH0LQfMbPAeN0Dw9bQLSY5LFNZJj5bglLdJJgeFa7LdUaMqtiU0GNKE3i8wsZ2MFzajffW+C37uHP9nA4kmM36jecijkrdZLKIU0zannNuqgdRcZRupgdKSn0LYZY3r38qgUpOSapiDTb3/zo31ZsiKhrGHzblZ13ACy3OA+AfgUP8F6pQDjiRd/BD/PFyB2td1i1oCqBGs+eHZwG42sWX8PeTUfyEZYEcvx3mM9nIb9cGnfZHJN2Sz9h8Syq1wJ9rIxLt/J45vl5MiplCC0MHuIQA6aRaZ1+AMQLYR5T7sEA/X05gld9PoFoqzzaa4u8lW9618eAOPxO1Ax4QSlEFtS2iDB5pB82+fLhZEKZ1FXjXp+WnZDM52/KvZYdYomV1skeJ6WkXOC2htGxjhHiTIYQQmandQrF9RIqWQBvGlC1Q==
    username: AgBPcc9BCPNbNGmI7kArlakXsnTP2D+ApP7n3Calf2bSKU8UjHy9c9vMC8UTJ9iz6kZ91SiacX0q5uEiTN8/ZsBfRwEUsToIBgiFRPw5okbImNFoDnXG713693cKTzxdVzonH8D02poKradbU66svE2QgKMgJq5EbJIlrv3wLXM0sMVsp/xf+PqbhLNFocgypuCST1Tzzk5BBw+xl5u/7sLCPIKN2WMER7LBz6muT6YvDDXMUnnBQDJMnj95SJBrDxazwu/QGkQn5Phm5rXu9qnRgYp3Dy5NYn8s20Z2lT7SzOb3vdNOdtca4r8CiAqAzll59z+ctZQ2zC3o1ummyMx/+FWixxs8bXBwbQvUBwWVimAefjRn9gXXGH8ZvVRuVE+QT+H2u6QP+XOoBSTx06D+xSrbYtSGN2m+wCQMhdlF+r2jJxNvIDKXncsLUAA5fs6xUMHuz1K/0uxR5nOanKMjl83WtAiDtNdXETjvV/mlDGHwoOD1psEN1GDgZz+D7nKBH31eiihOKTtmKC40/IUORFRolSQw0RK6FWUIq1yBEQYcoL+/jIPLw+9DXaAozngrHsG1CH3xEHl8sjmkL+SjpcRDlRfTiBGQCSeG2Kfh3ZVB8lihDcZcqhvgelIQZnfmo5q20277QXedr8dSU2BpJUdJpLecvUSaXgYHXKrh6P0vVHfoctaTQ5ggwGeQ8nUnNKuOYthPSkRuo7RzWUMpkY2gcA==
  template:
    metadata:
      name: paperless-smb-ingest
      namespace: apps
