---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-config
  namespace: apps
spec:
  encryptedData:
    secret_key: AgASsxV0/ER8qUwvlt9H7/fz5QqDEvV6oI9k+1Nd56BnCUdrcXQwQzYsO8e5ytcybk4QQigGKU3K0JGjQk14lVoRKKQ3hLAlrPANpac7lEyUxtA50Sm82902G2N1UFiaYwqiuS6cByIOdiyhrD5EwgKDy0fPTI0asZSB39N5vsz5ZBN1Z+IRQ+xax5JtibvKeZ3yLo6410GeTv5W0tlsEHpsLo5AQhLufrs0omrZwKc+3S5pvl/CiwNeprhBWFiaKK92z+htAIO1jgovoixE0uPDZP0Six+cLbkNvGRgmySafmPXvPBH7l21zKtxNDFrxfZA2uvUNZYukUAj0LZJvw4jTFPRPr+KvniIg7Z+dgypiYJ8Zsn0aDbxdBAqPNDKzImeFuMHn4IojPepaxhRv8QUIItSOaj3RgiUyK/GDuXxOtFKiVWu5uQ8834CDmUt3E9SL0OUi+FK54p3CXaDJuCBLO6jILMfdxCEnXd2/tjz8JeUZDUGa6nfeTc6l5pBzBGRnTiAEpz87yqRkvXr+C02YV0i7SrSJiVtJhppIqlFQpeFyJu42VnpimYaHBaC6begPQIljc6poM6DCQb3chhYKGSiPrGhnpOzv9bT3TwM+6QVJbnZ+0xEfnAurc9PuYE3V4sfzOZ/g2FljTk1I8vSDmu0WccP3U5eZgVD1lmtyLu7sgutwOdSysKU8+PuUO1YmYVSn37AnHpLyklgwySg7BJaP0YmGBM1rh9b8ENglV2LDEw1bsBTdFLf2WlNQZWwZyo0oaAqlErQsQyceWJv
  template:
    metadata:
      name: paperless-config
      namespace: apps
