---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-admin
  namespace: apps
spec:
  encryptedData:
    password: AgARplszTHJY+U0RmqmdtYJs+ECfRp7LxBl2yCIkaWkj3M4hLjJ5yW9JDQCR5gHnLk6UEArzOXkECrojhrWfjrxoebsD9bYZUYnJRIPmygMHXLc+X429OKshdQ7gSwPHBx7Ui5It44dmhD267I6YhJ+GamtTM8Aqy/VW66zM3o9A38EgmKunS/H2WQpCD+1RF7P1G2Wnwm+ZAXiWKngbNGG7vKQVegGSRy1StJ3jOcaRwaqWEF6DKCfI92Ia7Q+5NRIHvDUudAH5ldYXeT6poAbLJBT9KY1N/0u/BYFb6WigmEhuT+hV0Dc8JFa+kse7Q7Uw2quyq4oEg+/81zGL/+k3oJqFjM5ixRWUVMqdrk7wHUhv5JoNlhYzoxD7ac2OcohmCa6ik8CO0HcXYI2lOxA6hgbNM18X09JPIxodWrIsTZgzZhfuT/FmwAP8XCyGZfNPlze6PgsCo+e1RZaV4iIQhzze1tMsDkB3SakE4vTPSZvEw0zrs3uLBvRQwZkykX+e4AO6SduIo3EZbOzW+40pjP3iWpvn2EQ5ZHMl22iNmpOMG4Ivf4yLwOVZIvfVCsPw/D0x71kveyPB3aPnJqLElnKX+SMmPHQnNYhWh01m2hcspwwSN7+/36oZtH7jbaa12gaMf8jclUJdG5b5/gxTekjf77PehyHnzpkKq8NvQlcMSucIxMfN6EQRrlAPvV+DYDQsyzymUT0DIl5pVkH43NzmdKKD9AbqPhsRdnIt/w21jED0TkOAWQdNF/XnkOc=
    username: AgAhPP266aG2ww1FANBMd2w9prFBC6PyeSLRwIeSeLD2ZXtQaWrWjMNZrqaFZ+aXdEEco3Is7ULeiyr0G52WCS7Idv87loGjY9Eh59jF3JzjuWZICQ4sFKoGFUoLcRiJT7k3eh5dcHRMljtlha91A95jdtbUwSPhLvlHiaZNAJ31CX/HAxuQXTlzfzBPPJJG7DrBP0ZImvTrwxFcZtHByd7lQcCUiDRzFfYX9gC6Sut8ahq8tl8ch1RFbaWfF32NFmiUSmfy6Mojz9ijavmhDb9GHV+NhG9gIEdST4DNTy7cpPKlgb0EVaikco2lB415W7CHhkwSK05teRdxkt0z+Q525hOvQI0+4Gl+vaQa5ZakjyGGZ2KYno9ijIJLFdGWunYzJhxI4mCsScsQ+jXIJKhBaLpyevOA+IyLBIaX48nTlXnar/Q4v5e7m+2qpF5/+nLFdzRCfkSpDjPbdYCZmQmY+z+DzdP2yb7PoZ0pxUGjAJRdUrrWiUBuQP1pc7FiCukH/eMEUoETLT6CUnNFnJOOCk/zjD36AmTUIVWTToZkeetyVDs64cN+ieNAU57mEP6+gWdoAMKXFOMurggEGexZ/uVQtfXdQs6BY/XptLisn8EA5/rf2iI8Y23TCrkp8v4VVuvlCzbhB5NJ9bo7I9yIs15xWp4rlpy6wZhhxdqfugFzw2GDj7WyGd5cL/fyxsUbq7sLiQ==
  template:
    metadata:
      name: paperless-admin
      namespace: apps
