---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgres-auth
  namespace: apps
spec:
  encryptedData:
    password: AgCfzR1muGbWf1WgRVls/hyP0rxsmTYRUFZo8szQllYcX6aEyS/6olmZRCsRah+3DFT9NfRd1u79UjNAJHzbFzQ3S0ihx9aRLxOUy/YxjrgqnYmM7KVAIppBvZptIawUNuZBaAfwWgqkxz9uDe6/7rVkRkUiCvWHvv8zYsg/Jv3sbpZKwTvmhwWk2rozKQL0OHOHzf8O69sZNfNsj14vYhV3K6lbgSyr0M3Jh5qYNs0oaHOKYfSqGSYDzKlnE10OnMMBZvKC/b7c4FiQmS557AmMXMDCAbDD6j+Glt11uFEiio8s7C6HD8mrgmBmlRDIntgO2kjuEY20WYAmGH/+/CAe96V8my5Rb41u3tv1bjK4fUNDGz8CNJZox+5Gl2ZNvdMfYXdAIA7Q8AAXAkhx4JvrXutxz5kf7otSbraJ0sQslWg7aIac9GYEcDJ90JaNTHgLajkbRoAWGn/mQkUguBm3ek9gozWmU9YgYJpMKVyyTSs8cqkhH/G/WMmoOKhGO0OK8oopV+GMtEChvO/lDh5FGptKBodxvHSQbcfAATqnc8+c0Qkht7caWjBg9FcPin/cqpRtAP+QcyC77WcqZsG4AZrKgMDAninb1O/6fZbAhtog9a0q24qrdfJV6gWfJmHJqPryDip1o3TM3IahJXT3sJU+CVYdLhJCuREm6Qd8NELpYan4xE053gz2QeQSlP+pS2sDEvsdvQLZtDbs5H6pPbe6d2x4EEu7bmnGxpEMotYVr4QLWBO0CLj+xuiJo2s=
  template:
    metadata:
      name: paperless-postgres-auth
      namespace: apps
