{{- if (index .Values "csi-s3" "metrics" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-s3
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: csi-s3
    app.kubernetes.io/instance: csi-s3
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: csi-s3-provisioner
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 60s
{{- end }}
