origin-ca-issuer:
  controller:
    replicaCount: 1
    revisionHistoryLimit: 1
    clusterResourceNamespace: origin-ca-issuer
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      kubernetes.io/hostname: lab-ctrl
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

  certmanager:
    namespace: cert-manager
    serviceAccountName: cert-manager

originCaIssuer:
  name: cloudflare-origin-ca
  requestType: OriginECC
  tokenSecret:
    name: origin-ca-issuer-cloudflare
    key: cloudflare_api_token
