---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-secret
  namespace: apps
spec:
  encryptedData:
    password: AgBaVv16qPg1HkFzeUSavJHrGm0hDSelTm1k5rFr4JCoOLqeIZ5zbT4C0pv0j0kRuvCnqv8yBe2N2hh7uFWdzopL5raDkH1rPBVFXXT1r0whprhb4Z4I05Z8JgkTVr3pjcRp/ER+pxg9WVafrqOd+EN/FiNtCkcw+kZG9Zv0IJ1u0ksdz/t9AOLVr9B9SBPI6T7JQsmIv5iX2InB0XMfbKtUfd4zhzfEUfMznIHtq7hQPCQLMGE+f/F10+LLDEEF0DrY5vhqpFOOjy2S7hIA1gKimqhrQOlvZw3gOY6btK6tUxZ8oDO7F0HXxVZzAGDdzs4uya0XzzXQVHPCggrgaPcn7uoOKPdvKtMLzfhIA+ADv+xz4dCtBC/knY7nuIIsHeJXKVgDfYSfx1KMKTWVoGrKwZvQiCcHmZc0DZ+ldHXX1Ornw1Z87APBmgKnFaphfgK3TOQZFtJA5HmzZW+vAwmMzLqsKWpyyvfpTrpLIw/vae8AgKurRBR3N0ZhzJixOV+zOMieAAUD372s2UrIHulH/fSFi34vqU5dgfXAqHJNOzBxooUGufuWLygFVh8cXFqmrGNEHWflTS8ovHtYYIGU6shHnts1iqz1R0wugsSFVVTwhaapS8/eXxzdou05mQKJ7UWXVqgefRfoKBEwIetgwEcQablpnu2D0qk9dczWoc63d2hiT0NCZ3DZxk5/eWQqTn0yPjQsPiOmLb6lG+chyeV1vMVh0rm1O3xw9K3d2WImUL91RT1IUU7I4w==
    username: AgA0bSGbVLnh0n5zSW7bO6XOJfeJ70AwA4mBFURtS0JRWV8eyCtxLfhw/aJX+RHyhYV67rkjGl7O0u3GY7XYo0vEvikfvwy7TV+/LIzphf1e41VXoQ7/2cPwRMZUV77uMQXyErKVpd/Ajgc3yFg3RbO50p5mwei4rNVbCNQPRyVQ8Fhz4YrZ2Ii7/jDo0Y3rOZBjfxRccRBNPTMF/Cbp9veT9v8Yj2Z8h2bXY+KAUDACqGSdyfmiFD6dAjADG9MGJIiseF8UXBxHnUCVYe0iJXiAfBfAF7QebWe8pYGwQzUwRNoq20N7FvD4km4mwbHgkqnH9u9j2UY+PUG9KWNurdMhf3MmFECAy4cQDssPYkx2VXrojZRQYMHacn4C3WNKWn6kYN1wK8w3TBtT6vaMAs3mGv8d6SMNF+wKHMdyeMbOIgn1HlYlgcUbMwvMgz/0rWCd2wlYft9nJG2TF1ur3drfBO53nrX/bh4YJ62T3ziIfRvfu+RNfnZkFwP8w8CH/yKJ2sz0b8ETD203FvwGHpxM4PnWtCr4wkJMIYhRkWr2UHWL+zSFcQgfzZ7oI8l+bFEieBI/awEj1MflHo5xRrwVm2riy3z1j435ML7vDhFwTeOKH7m7arkD3eg0nNBpfP0qdsKQdFbUDZJ0wEqpM+V5kK6E5s2By7n87VV5P3FFLSdHtA9JVveVdz2NAAkzD4p+6VdoE8Qy
  template:
    metadata:
      name: forgejo-db-secret
      namespace: apps
