{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kopia.fullname" . }}
  labels:
    {{- include "kopia.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      services:
        - name: {{ include "kopia.fullname" . }}
          port: {{ .Values.service.port }}
          scheme: https
          serversTransport: {{ include "kopia.fullname" . }}-transport
  tls:
    secretName: {{ (index .Values.ingress.tls 0).secretName }}
{{- end }}
