{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ include "kopia.fullname" . }}-transport
  labels:
    {{- include "kopia.labels" . | nindent 4 }}
spec:
  insecureSkipVerify: true
{{- end }}
