apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apps-root
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/instance: woodpecker
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: user

  source:
    repoURL: https://github.com/sm-moshi/infra.git
    targetRevision: main
    path: apps/user/woodpecker
    helm:
      releaseName: woodpecker
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: woodpecker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
