apiVersion: v2
name: cert-manager
description: Wrapper chart for cert-manager (DHI images) pinned to a vetted release
type: application
version: 0.2.4
appVersion: v1.19.3
icon: https://cert-manager.io/images/cert-manager-logo-icon.svg

dependencies:
  - name: cert-manager-chart
    alias: cert-manager
    version: 1.19.4
    repository: oci://dhi.io
