cert-manager:
  installCRDs: true
  serviceIPFamilyPolicy: PreferDualStack

  global:
    imagePullSecrets:
      - name: kubernetes-dhi
    priorityClassName: m0sh1-core

  resources:
    requests:
      cpu: 10m
      memory: 100Mi

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: lab-ctrl

  webhook:
    serviceIPFamilyPolicy: PreferDualStack
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      kubernetes.io/hostname: lab-ctrl

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      kubernetes.io/hostname: lab-ctrl

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
