cert-manager:
  installCRDs: true

  global:
    imagePullSecrets:
      - name: kubernetes-dhi
    priorityClassName: m0sh1-core

  resources:
    requests:
      cpu: 10m
      memory: 100Mi

  # Prefer workers but allow light scheduling on labctrl.
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
        - weight: 40
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: Exists
          - weight: 40
            preference:
              matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: Exists
          - weight: 40
            preference:
              matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
