---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanopy-daemon-api-key
  namespace: apps
spec:
  encryptedData:
    SCANOPY_DAEMON_API_KEY: AgBOvhIPfv2DcTNCD0K78nc6HtlzR86qNoBfr+RdUYi4zy8hrqRmQYX52KQM2YN09fmkk8n0x0SmTQHhbvEHIz+CqvYmUxC5WzbrVWmIqserxfkJEAUcTuHhkDHAQIv+HNTV3GQJMeLKDC1+pUVmfai0eNgSzlm/pslD5RduwgjtkXRTCmpP1/FrubYvJLbnBhpqRie8BOHyeSPb63YhQhEkna3n8AW1wJF0gWz/wYQiEkUBY2zG5/aZyyY/XtravN+ASvxvWbWKTdJ8b6Z3x0RHbHzrmehQdBo/UquOkCHsBRYW5L1PJG3VA+Fp3yi1It0kqBIcJhDoexEhrLOMeni86kHEYOnMwOuAx6LJOnPYcGmH9PaV5CXPQ7l8vlmiQPK7Ih+huxCHnm0pQAALTBsMe+LZytDoqPpy5lB3fLgdS1lA7Uf85m3JtBACSqb5bRR8WLWqDq+TjFMfYksUrJo7+kCeA9bV+GtaATlvnuMviMU7A1pcuzSRgLyd+YmmZKTRvH9Rvn+tPsIk5hIz7GxYPjJRq99N9DjqRwuVQnzOXb4sNQOuvimYtqo/8/qWKDRNKaTV9SH1fFrNIAse0ECafbXLQIS4oWBumDDYaY3yLPQ32vfflqrZ7F7rLdvLTYEqAmYKFrVQhL8hj7/29h4YTw6GN+yuak3snMUEhC+N3pnv7tHVf9I25IwjTGPA4NphT/jhAjgFeduG+RLfvI1rFkOpXCeP0HyefU7CaNdW6rzI/7pdsQ==
  template:
    metadata:
      name: scanopy-daemon-api-key
      namespace: apps
