---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanopy-admin-api-key
  namespace: apps
spec:
  encryptedData:
    api-key: AgCOFEF5nB5w4feIp3lJgwcxtScYFhxrvRgVZJ3ae89d6WiaOEkvrDs4e0K3PIrePrG19H4E+gDl3DTZ4271kV/lvIiZmPjMh7liu0noDNI2wAXiseWZ5VMyFRbhWW9XcCgyYTQUjnrOu6/KqhE3iwskVqRrU8EFdmjFckPpACPhXBRZW5NTg5ztQ+tuHpyb20+bq9LvRgKWjeQAI6TJgSPc5bh5BAJucTPPoilMp4lbADv7RW948b4Cw/dMa4DWTxHxapupA+Wm8UkS2aAaHXH3tb/LuD5010uzvd/Q5I1XTb1X9yP/Ion3PTKXoRnlOp9f8E2t1JyU7kwi0uc/0/YXbYFk5sWOipgdcN3ALpCnVFVZDHDbSLkDlJgUEKSgO/4Q9y6b66JRCLXTgVf1/dqIzvOYJ29kdwI9AONwbhjYzcG828esvjw/ijeMakv1rwxIPP0tv/WGUeTTt0ihwL5KjOil2MlycU3N7mGM9iw+IGWwjaR6PUmGdJKiItXaAc8+AQsfC+UO4h/WaafXz0vwkNdwXYfrBH2nh9t1m3euz14f57bwXrJTlLLnbiCCxbMgt4GhVSfP3/e+GHFS+xqFLgHyXgdVJw7TAgOebTFopU0YQ9P4tiEexOJsETOY9/3ScCooPfsqLwMRtcctGkIqKTs6rkrd5dfDDQvmODPPOJUWaJdBwyJ3Z+JNQO/LtrIeQKAM4TPvLjJKsxFkX4bpEMhCWUqS9nW9J6uFh3CwcUsfrjxFIg==
  template:
    metadata:
      name: scanopy-admin-api-key
      namespace: apps
