---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-oidc
  namespace: apps
spec:
  encryptedData:
    client_id: AgCG2SQekTayigY9riWWoB6bfW06NQLInGKQ+90x21vnB2WnVtWpPbJcfo7ASwjknVsLGWncUWRURiBUYqGiH+LpFnytA1cYOLfSZkf+wGLLdH82ye2Ug/Nfs1rngbjTyfsHQi2hSPoTsX/KSwAmfymxC56agh1anD8hjdsbZ8rFiZwRTsEGGviuCov8BzYyyaItHcWx/+GDw3i4BvsSYvu1BzJmjrBZ+it+tP74G00Hy/JQlrjIGW6Gjwqg1R4gpaTA3yzxlmj4DlKbqdbzQsGfaFUDnNS+WQiBDfsrvqSt3vVtx7hT45zcCvRkFdrK7ozvz6qOFMCiQ9NAhqCeH8M/xiGqyYvqYk95Wh8ueWkIFIPRvAmMvDbXw7vVS4BFFwFTGmQvhcuX4/Q4B72Nbs0fQ3yDKzFJgzh7IrRswD0rFdMGrH8O51ILlhwJE4DXvr/Vk3S2ssVd2698HE+mDx/jHa47kAXQI9IKoqdkvZjFsZoP+L5deVybnfr8iI4+u15e0ern9pp7LPBusmXfIMZYCYMGl2qPah1hjKNVQ69OXPLAcypFqfNc6z8GtFgGjyrwKCSRJSAtoA7nzs6yvSZTu6u215zCiRJ1vRixqBZtFnbJIeiqd1/6XLTQAgPlWHk7raXCI/ExWkmEsmMJsAZzlei5zBmHaCmE9ZHcXUM8+zJBNJ2B9Uy1vwMfk7UTlqieKHtI/SDM7/+AZKOO+oExRxrCSSe6eOV0+fUJ8g==
    client_secret: AgCRo7so+/L5gzRPSxpapxEGjZ2OMopLybSY7kMGox0blfT1UX4yBMhCOP/EoxTM+wxXWFESZzQkP6avpWZKIDGUjav5G6754WDISry76N3GCYFS/kdhbRzIAijZ2n4Tl0xz/Gd2R5zwhVibllBmcpPj3EARqH2H+oCNWvLLIgrJfamm2Wh7vt+cvQtO4P3scON0L8xoIgohhz/EqO2wlYAMyP/dyHpV+gORUOWg6lb0PffRj77x6/zJfbzYTSj0vSJnWAQSimS0OmDltRf8ny0KgqMV0DSL+5XZspJ1w1tIFMH3MUkase7rZwFDvAFqiPPlhAOd8OO3amKIVR2GR9Ka1on8a0LB/Mf34NZAcY+UkAquvX50Ktn4sBTvoMlSrLF+TkODr4Cm4nAWFF2OevVlvxjPTdBixRHFiMtau1USsbP92Qbx5Oa9P0YLcFWK5VIjPVjGYboVb13vR4XlRzGLxv6qEF4KtOumXyvtVi5wWxE8FTMlE8mlsJB1KCkZrqeCKtbkgmY0h+ohim5qFq6oxBfDWMXSyDRn45M/fUrdgjWZ4KtHwg2Jzc+VlSq8BJ43AsV11RDS30ZdqDh1AM67gcoCrZzZSMRaVa4ENP0rL6rUPe+yYtPySuo4uURBVdQc0QThYem/GzPB8TnMWtHSSdTGthNCs4exLVnJGhGhug7czYjfbk/CAqMjcZMn202yaO3z4+4aVpb66rdM47h94aQ+/aazz4+PZdpM5iBL/Jw0qy+D49yZZXhXJA==
  template:
    metadata:
      name: proxmox-oidc
      namespace: apps
