---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-oidc
  namespace: apps
spec:
  encryptedData:
    client_id: AgBztIJUuhfw5R/YKD+ct7JzMKNcVLmPjZq+GX6aAsQWNoHwfrBRsOzCXaRx+QfBjSjesjDIuiaz/gsRmSNR6nBZkfi5pExicTSTeGsueRp0YrY3aSxK97dVAJ/mcGpNVuce/WAKzJOLhHSTBQ41x23nR3hs/8Pdh5UJsXZdTOcC6TMgNWxvFwlGJ+jk47BRqJ+yb3Tw1YSHErjRMhPFAM64ahz2LA/NrsmS0GfkGb+UMiQwIZ6J2G4/KSFE2Etz3HP/2mtERszjnRgjpy1HrAqxYgom1HQbsrw3Q6Dz4gEz95dulLXuijXhGlldZmBisEqjDvFevMQMjjSw+D/SOd5w3wqm7N0v51sYHIuUTVHs2ZHdqRzru9Z3sVB/DPReOYhThALJuMEwD94x/gNjadrN+vwZ/EL36Q8pPByWypCpMD5CG/WuB62NuR3uCb6wkOVfERZ4097ELxN2wDITY4Duyl5YgoZTUfYez3ptzWoZLAHIbsGmAlyaxAeaC1GkIsNP89a0X7VORDMBZO6VEqPY9Cw7oe5plsMdQn1QsRqdwn1dQPAdVjP1IBr+Hz1sXm/G/JSK7Jwyc/92e3CS4DE9PqX9g4QJ6kLfxifuW3D2x93kPaQjzq+ijSd4ZvV6V64wc/eExasq1PjTlheCkRt2W4HSEZS+tfiaHIIgfyDqJb04L1J7r/Gl/2iqMGkZkcA2fcEQQMhd46gBNazhLKpkPnA5T8UHpoATPkDIwA==
    client_secret: AgAjzFbd6q85szOk4lLnYzUGdllJm7UW+fDGczHi83d081G3IuiZ+INIY7Ms8SI5GqOx8g17b7h98tUvtUDuSWk8TjrEfbJ3TOdLUNSrAOzeTG9ksKvnytkGv+OKqfofCIbnXEI+X84/RoVf55/2fYA9hCD1fz04t4caTkR8JKCiekn79gKSguKZEct15Qi32Gr2rvodQpbe0UxvE2ECEfSspNU3wi1Swef3cn/ntYbEnVUR6EWaBO+SxvMxyjzF1l8Mk0DEI8jfjbmhh8Ap0Xe44H9vR+DHfpBTivPctqHMQ32iwSAsVQ5Zq1YC4WRvuVzjfdP+L/2ZIMlpyW3ZEbG8EF0BCBLiVav5KCrujfybtYnODcCoWsyjsE/ACQfqJvmEFS1HygUOUbct7+Gy4hAxvB/hOHCgRR9kZWW47KJyAy87eMakG+qWkE9tJYWXthwL+mzkOnkdxPWeS88ZeQg1g9XgAoHDz4joTP00hcH/eaB4uFFThN35mxgUU3Z32phzeG6MSODORzn2huruz8P+yKkX+ZV0BDhLxvoyrhrefeHpH+xu931XQFeq0AvoR8LZc7XVvfOWJRjZU+LMGQkwO0PuzL8Csrm2HJXLfJLDsEjOrfjtPSt1cR2jtpQ2/QIrgzgr7aHzM/S2U1klhH0fHqmdqBJ4fh9vTZSDYVQorSbAe3cih/lU8WsPPgmHknLXZhmppOjm3ru3YjzQbRm78g7ezbxnaSVpVZ6N65OJ9wrVOZQcOHPSKohZZwbmQYuVkWFr4zhVvyPcS1DyAZWt
  template:
    metadata:
      name: proxmox-oidc
      namespace: apps
