apiVersion: v2
name: woodpecker-stack
description: Woodpecker CI wrapper chart for m0sh1.cc
version: 0.6.13
appVersion: "3.13.0"
type: application
icon: https://avatars.githubusercontent.com/u/84780935?s=200&v=4

dependencies:
  - name: woodpecker
    version: 3.5.1
    repository: oci://ghcr.io/woodpecker-ci/helm
