---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: diode-postgres-auth
  namespace: apps
spec:
  encryptedData:
    password: AgCawzpFBk91GsUmyeXDGqmvsPZUVNYtrcfQKjNH9yKpqjg+szEqYk1rjLcjAPzkm9u4Ec6JWaZ3hNWNCUI7+hHIiGtS8DbWLkYl7XAL6/j/Po1SgFtG2TBbNkuG4lVIhJfyZ/RsfJ3SZb3fnB/gMCLQK0ezyT9t1Y/HaN1NA+49bG7JX2pVmzDCIjmJkUtv2lScPLAs6WkhktMYWYoED/3En3Zol2lmlJHq4ZvpMMlLEMteBGr7LaCd1dUDQc7V1kEjphep7smzaOMOzND3VKiwotG270jlMJJqT1e0knsrTLJSifZGR+JzZ4tpdL1fVDoa2k+XjtS0L0/RBq9cPh9y3xCQzLmVUBSxOpfjClCCH5mPvNWZqtZ6o0ex7cJsH0j5FEhPXkq/5Nm3vY2iL3Gbst7bsho8DNty87kS3jLIVWTm+2/zpJROJsWpIzF1pPIb0wNNg4ZxSD0VR92l0bbjavgaXIe1mdgPGf8WwmXRlqS4QMJz1NXITCLUJU+W5L8QQ/JHLe+zomGxFcL1M4LVHBCTUwSK0L3MQsAm/LXf5DHt3JYB4GWOuugoSaHCxEdZyG1TJ459TDXiQtvOyAVlODl3A0M3NgY3JuURqpYOYLKIlKVSTIOpP2H5HCC/AHTxtt8FObdiFDSfLmYLiELXIVkhJoTjon7v8e8rOQ6B9v/kQWqp5+KFtyCxIcmPmGmipBAml2IxSR+TjXFsW/VbbJDXnqgQfw7ZBavMuNJDgA==
    username: AgCFEEUnZcVWvaAXWQrYrsW6eMbU3ptybGH2hX9w+XK4kYLGWg3IKyhsnF8hiH54XSSeEtuZh5ueNZFgFIoVD+yur6wWNzoe8Lfa+0MQgmivsOMdPkb3jqbuy1PFCSdllH5GybO5sahb1O5f2q40Eh1PRR3HpzY3Y92FunWU9GwY49GY059UK2nt98dPCGkymPzolOGhYFkKUdvvmHjNB/s3kQ4y+1VEbmoTmPdSL1R/hSHyrKfilJmYgjx//1HGXneAjRsv2/Iz+R1GmBH54OpXKNyXYj10JFutX5t5I01NOKIRgZ1GYYXQ0fDX2p6ZScUHnjVu96kB5KoMoTz8pEYFk/KXRvU+LZx6+QoXZph2NOq84YytSPUMvdaM3jbaw37NNTEtk5aKPwI3aDqBdQTV+Retn2NieA4cPaH4qSUiHTFwN4AjTbZob4hIG2DoAd/b+HRVXwhwADD6nFYpjKpO6cm5zioNKY1dvjK/br+gCz4fqm4oTQSw3nZAegJvngOkU3mH8h+uW/6FKRb+JMPcBZjc04tWzXcrPCriNd+T8KIdRV4vxHGSWBXGXWmKvCSg2C7CMOFYCb451IdRDxVEa8sDk0uwtfzKWdh/7eA3lyYC2MxoT32jneFJmYtJzZvdpclgeOTefjQWC5tbQkVVzFUs59z0msrAB2hMIa9feAIT28NjirM2TMaTmrTLmY0mzqBxlg==
  template:
    metadata:
      name: diode-postgres-auth
      namespace: apps
