---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: diode-ingester-secret
  namespace: apps
spec:
  encryptedData:
    REDIS_PASSWORD: AgCIWpLKnMckMDSYepUx2w6LWV0KfxWskWYEvlEuNrMGMFW0gnqyZdCYyH91U4wGqBeEFE6ywAaaYo8Tf0JWGZhRu4H93UCHS9nFuGmPr4BK/QrExtwwN4mQvQd/UFEVTC/KHLFvqYTOQk4nrrO+sgLFsNOdtE2cdMVuF9wn1qxdlMDu2+cl20xE1N+hl72rrtubiqWRJ5hz8rfhYJP7oRHI2QbvGaZgiokfmZs3NKLYQUPSn0QdEO893F4H8TQRBrQMOiyJ1A9GL3R+eMfEZySOLqCbcQr4cAcglfFwk2ly/yzJD6MwtB4La1p9LZ3ONpN0xSXd3WV1+hq4UowEEhYbZ2bEYd/7GUXGWkQplw3Os3e/sNAWmbSmy672bwYyMIKODDkbx36OOizNN0UIOGogTZUeSDnSy9PIY+5Jtkz4VVLMDp+sYePg7CQhJ3IVTj7ue+Czev7Y4N48bFEZ35Wfnn7r7sWy6lsl8VntRZHPEsNCElVjWEcnQTxoI7TcTXZhshMY4SZld9ed92RTIasvucQ1WGtdhHATJ4QeiMYgytfehuFz4EbkuU4SEpC4TT/KELkTKgW8QIE/dBUPG1JLES43oSkleloB6KeL5vMV6FPMjiKJAqMTaP+qn3B1y4lOnJBJDPUwOQKDiMLrJLQ+WTzgE+lFb1jBYPEpo5KpDFmDJb9Zso3xXc7vO+bqGCY=
  template:
    metadata:
      name: diode-ingester-secret
      namespace: apps
