---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orb-agent-diode
  namespace: apps
spec:
  encryptedData:
    DIODE_CLIENT_ID: AgBjt98Qf9ZpHPSzMMWUnp0JUwBcyTg1PGZKr4JAKfozBMhKq87Ujra1qh4xfNNMPR1dTZ2RilHCFBFrYIPjAHskkTAGZwPTXu3el2ze8Lf035McqchEfMn4HgD6QwentL832HMfsLohDsR6iJ9o4FoPHBdb6S7UZb84hSIiaMFqzCoY04FJ13PTVBtnABiyMceyPljW7XqQv/tWXrCpJCcw0eNb3Ipa2PCbJCHb+WRuRZI9tCukLWK62kiEqGPV/o5uPr6yMX82fySWHq4Kwm5YZ46ITBVZpwfuFYbcEG+3oaJEe2hx+Y70E4ERVK+Kja9YAslP+Qz+zorPl4tdR28ntDvxZjNGoS1k7CuejphlHOJ0UqtbbRQFK17e+Wi/TZc7IN1CSkVMG20xUAM6CyX6d7vvmMLcChjf7l/SxivDfzj2dXS86Ug8/xHPCPjasMLL1sk/ezbasbA6mtHDlSYVmB/ROs9OJ6dix5q5Cbg54ePfynnr2Jx4AzQNYr4VnsDYgFYKn7ZehRmjAY7JY9kTcfAcuBxDJWWvvem99MKt3xE2H8WmJ2E0Dd3qr5kkd2zLWUu65um7wf+vjrmlbfVNfGRStJqWYnorlKppmIC4558P74AyMiuNxgpcRnTwnhm3Qsa4B8m6CqiZGWz+UESX+VKLUGC929uSgk1MwJIgnIJldvyT8fWhKQpYljry0934qUkxb1R9Gi8mRQOfoXZlAKdg0r5iXBlRQBQE9rsoww==
    DIODE_CLIENT_SECRET: AgA1OlCNV2bkXxTBPxlIVuIVMtL6ZyhtHLDgqN/NPmK2Ay32WoSR3enZan3kwTV151CiZkONPPUo9PHcWBeKMj48Kdz5KjQXKqqqUw3XQ0GKSmYVC1YMABX4NoOWKTQaf8OJ35U32KJjaAwM4Fae7Lx35Yt6d9SF4b9yjRLrOxqqQ7XDy0nLXtpdifSwM9FIKIScRK/MZ7s3uOwNWv1SqrGCuZYCFBJKHE29E3KQ1cf37q7BuOs7QzjXkbU4nd3MfuAaRjzx12fsHg6RMlqmutzLr7BwFVvPB4PA1cRxWzxAUy0qCFJe03xjEbsq+Dzj0HPLMTb+iNoGtu6LLjIy87qYNT5wGnT8jxpGuHoV9W6wywjPeK0bdVaX8XiBFAZg1C2Cb/c6EDW9ucxbeVb9EtaZJNsLGuwsEYRsBYvctboLdqu/s3lkXGiNAI0XUjzwAj+zDpx9qVqI96X7bIazvHMiQMrLLzjF/5DhdPMvBzxcpd1ooBkbpH5MwRFMU5gpBcHJOmiPybUNUkiDkyGzropx0d4OwulfkqN3kqB7hj4j6mUrQu5UQLAkrhU3FEFZ3CIg1dygYnap39aNVxrsIUuiwWeuIdTTfH5oENiYj1CkXOAsK/bOhrI4vQ9Xo5zpyliSx/LeOZ8SKnv9jMHGC9gHtxSYumv30CDDz9OqZIAL/Y+yFtaZnG1+TbxlDreOW1d9o8+3hgTjPP8nix9foGR41KpT8PTFBFREOlPESK5kIrpThuAoqz3xmoPVpQ==
  template:
    metadata:
      name: orb-agent-diode
      namespace: apps
