---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orb-agent-diode
  namespace: apps
spec:
  encryptedData:
    DIODE_CLIENT_ID: AgBSWgMbDe2WS3sVGo1GzHRgDaOgcbJzwkrQc+7KYx8TbBGhRueq+CKWYtvp3M3Kd3XBRQpUj0sHVELAsq4NmokZx/QEzW+pV4ykRlrtN3rsG7s6Xub3HSuP5LgpNzKQ0+brkc7NEWP3FN7ODW0qbsYlFSgEco10bImxAHfGPS0tOM+JNnN3Fj5c5yUPkKfnIQi1/n5tKTBjXDLCuqpMueI42PIGFR5Z8REB3blh1+5e7thtyUpPrdw8ATFEiPnrxX0l63VlRAm+TZRZ1XJ8bU3OnZaf7pSkkgoQ4GsU9tjQmIqoC5F4xqfimXCD5KXgeA7kPCLDCyhngFcVc1jggGU3N6in27yr2F33nESaqeVftMswcLniKT7ATAI+HqDfMZkKe5ua1o4Gls3Ew1de+Sq+7dP7BoBS6GL2eLpI3HqSRarzNbawgdRb+ZFjAM1/f+YPxDDsSyNJLiB4QLIixydkmXlaN4rJ7BWiq4tl73S2Wk77lEdmsmP9t/UhmQDGkJ4ZKBAlXkib5Z4PFBV2MpXgHAy4kJknhGhefr6r1qUjbwqVTO6gSJycGzB5paC7rMiw8IHGQzJUP0vHB2BTMiSwney1VIn3MTqfnvFMZNIgJRNkgmeriWEOgmsdiNnyNWDSgqNYAe3Htn5yUjQbjSc8NU8Tcc3qw5vD7zomCJ6YIQGun/JDG+KCTaQ1YgEx5dN7KEAYOyplilVyhShuWg4A2cAm
    DIODE_CLIENT_SECRET: AgBUni2TAPoYGRairnAM/gOuptx7ka3iqrW1K3+Lt9/1LdD6CVh+ln7d/DByf8o3tEY7mSaLTgCKug5IwCLSprSKjnmeR1Fis0zdLrR/qGALQec46SANkN2CxEPFrRtpLeN0Jvj030tNaU6r90YFquNMkBm58fL1ng3+RzUOXBossrUMlBSf0yJcDP2CVZ3VbldjewxPqPW7oQnKr9XlAWnRLeIQDQfDNnKNEhi87owG6ZTcbTTJgYcoOD6hTKH5yGuLCVRUlK/kTCNi/AP9StgpJVLzPnyVjhXx9KWC6IPZPzj8m99pCrgP5SZKBvCDL4i+WTnurgLP1NeFSwjnlBpCQa03s+BGKt/ao/7z46kK+adp7Uf32yGFq2fgdFdd0jk953giTmvHgdUcGVcClBsvoOLNf1QlfZaVgv+AUQVcbs6ABlTeE4MC0zpWCM7+QJiqUqh8Yu9wHgNjM4VkbJip2KUmS7NaQkJgM3XMc/NTPmV+ZGj+ng53JICoiuMszdc8cjj/f+B0VqTwOLpmQMHATM9TAQh3IG2ePXPSWTBkW4Lv1Qw/ApPXWuMrxepkqi2/9UsNsyX+NK15AAy2GAEavLF200aJ3/PZOuwuKrJBI7cqmILoXH3GBY32Ct99hLxOno8vY1HERjimDpXEGOyJqRjUUpdk5rmfqzIMHkdmQC4GVoYLRlc19XoEesTdp/0AddJMJMedYylkaCSyDuNyYPZBStWtH7tJvQtYvgnjT51dg19zzubCbeczqy2pyOxJ/DtEUkZC/OmXXoqmYSpD
  template:
    metadata:
      name: orb-agent-diode
      namespace: apps
