---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-harbor
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAUFQFJ3QoYEeVRcmH194dT/WQ/XU4F2ksqm4IixIdYG5N8BldHjoQDErh/XRkCxar6C8IFlKzcC+fj/g7C87gkUyqR/Owqr31CRYKC+kMnBhFA9AHDtryXe7yUX7QkJzN/s/S5EK9hHl02gjJo1234Eq2AYjvfpYYzHiFrQoY7P7knrQm76ZRiOJRLUQquqSe59VXDK15F4v5aW/frOLg1gT31thbOzbKTbWwceemwCFmPw69vrcFekW+IqyPF4vz4pPgsJDS6PrlkEJ8cHBnlGShTjh2sPoLTqPIcECPM4I1qJ56mCrgdXL6u1EbzU+mFrWGNYlicrJCxKoIM/JVFSGEhrIAodCTY7i3D8xXgNPbqVxNOoOrFYFy2QD7BGh5h08fvqkXnyaUc3BGJYZ8SDQMeEMjZD++/0IkQ/BGFYdMfsManI3HIjNGH65PkRTQjBhnbffol6aEfX9HMGgby8Dns5WsXfEHYicpr+XjOhn3p96fgYsJjy6YHS6Mib+gpndrNx0FmOoszw6xZXuxZJlvD5UsF5txUTcokYExZ7070XMCHnfp2bnQxO30CcfXpSKIwQFg3b8VlPs43tktX/MkeqLMZycENzRdM6oZRg+I43cB46HBw0yeVsyQKdV3G2mlXR1qrY66h4as320LneMj/hfK1zrN3bkO1HymMrfFz2LSIvstXSzo+7wkRbmZpITCeVnFzCpl12XfThnEs9qy7oQ9MJzVw+MI5ZgIqdiCu84iKp2H4OhQz6diHuw5sv90HceHCbEXt92EZp/JcVupzJQARu1v2MNCEr1cJKoLxbKOOdgs0eaZLDliWjZD7rre1ZSjnTv+NIeinhZsUFi7xKyyRbIlPpHKr2vY8uILeDxS21maUyqzPAVcI5wW5Be9/eSOkR2PqkvqSlkAUN5ZFWi89NxTQd5LduS9SMiExGmx/LdlV3LqY
  template:
    metadata:
      name: argocd-image-updater-harbor
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
