apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Alertmanager
  - alertmanager/alertmanager-notification-secrets.sealedsecret.yaml

  # ArgoCD
  - argocd/argocd-dex-authentik.sealedsecret.yaml
  - argocd/argocd-image-updater-harbor.sealedsecret.yaml
  - argocd/argocd-notifications-secret.sealedsecret.yaml

  # Cloudflare
  - cloudflare/cloudflare-api-token.sealedsecret.yaml

  # Cloudflared
  - cloudflared/cloudflared-tunnel-token.sealedsecret.yaml

  # CNPG
  - cnpg/cnpg-backup-credentials.sealedsecret.yaml

  # CSI
  - csi/csi-proxmox.sealedsecret.yaml

  # External DNS
  - external-dns/external-dns-cloudflare.sealedsecret.yaml

  # Kubernetes
  - kubernetes/kubernetes-dhi-pat.yaml

  # Minio
  # - minio/minio-root-credentials.sealedsecret.yaml

  # Monitoring
  - monitoring/monitoring-grafana-admin.sealedsecret.yaml
  - monitoring/monitoring-grafana-oidc.sealedsecret.yaml
  - monitoring/monitoring-grafana-mcp-api-key.sealedsecret.yaml
  - monitoring/monitoring-loki-s3.sealedsecret.yaml
  - monitoring/monitoring-prometheus-basic-auth.sealedsecret.yaml
  - monitoring/monitoring-pve-exporter.sealedsecret.yaml
  - monitoring/opnsense-exporter-api.sealedsecret.yaml

  # Operator
  - operator/operator-oauth.sealedsecret.yaml

  # Origin CA Issuer
  - origin-ca-issuer/origin-ca-issuer-cloudflare.sealedsecret.yaml

  # Renovate
  - renovate/renovate-host-rules.sealedsecret.yaml

  # Repositories
  - repo/repo-dhi-oci-helm.sealedsecret.yaml
  - repo/repo-creds-github-sm-moshi.sealedsecret.yaml
  - repo/repo-github-m0sh1-infra.sealedsecret.yaml
