---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-gpt-config
  namespace: apps
spec:
  encryptedData:
    PAPERLESS_API_TOKEN: AgDMgHsD2ZPnL6l3cMlDYGfyeAFRavm1Ohi5JqRocCRDAR7wrkjwG7FHCgUPvuYa+QGc3kXfE51NIrRuUoyXwHymCk+mnEbRidctfCj6qOMW+h6GrfYQ4xCaZQnlUbzgn3oEJndYqQA/P2M+YLrJTVBfsRPvnVM44vbciQ64X9kmvZLZxCqbiY+dHCSZfH+3eRutj4abKmxuOJLnOXPO8g5p17oZL1E8+0u1yQk4VP5fsy2Aq5qtxHHuVIQFQtpqmtUlXJ+RX9i+fzBL+eorZMUlf6SzMORhQe85CQPvLGUbXp15pKlTBxpRIEHlEWAn/11JaJCDdVorbIxhblBGd3QMMYHjMYYKICCcyLlAfEWJTyY6cxqvYQUDNI3bnHb+vNEAlFmyFpPE1J40gxmrqplJKj4wdyyQvq+9pWQ7dd8gzCOIOCS1wor9Hu0BpPq11WRQR/g/Y/q46h4EcaXBrSLVFIZf8QlcD2YAY7GOQ4HV5Rude8Sm9qlbC3ghmnRx472/eZUGlC02xiQQl6+fuwddivlZ2zEvP6lsobGBqJR+kIk6T1LAURU1HzUw8l2KtTi4AGNjk9bVymaHkwTWdBKWte4kQtz25jsu8+HKOyLzFrzTUJNV35PGICADfk/FIs61PbPisZFzBCwW0PtQr6vTLEUJdeLtUH9QF4Dh5Y5QdqQafEMiGP58O9Qjir97jhRYZ2zlpLA3kSRRTAU1C5Y0IhwM3deeHeoIP2Io7pWjfw2RNG1zWg4R
  template:
    metadata:
      name: paperless-gpt-config
      namespace: apps
