---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gotify-admin
  namespace: apps
spec:
  encryptedData:
    GOTIFY_DEFAULTUSER_PASS: AgBiQcKBbgvwI4Ljt1R/udGg+BzBjagj9hPzkCk3WRic9hPjASlve5tP/3k7rYKx9PyI2OwyDdjHchuKGgyrJaZRzZgqIDTHXtK7IorJoReVrDe42umdEH42gPl0DUBxrvRdqjFbjNX7159rit+N3+nBO4JStoATLXY1iVXVzBtN96lVQJYEXqkv94d0XoP4syY6yRAcPrOTKASVpYGveysE/03gK6RCIgzCWOT4pR6mGXdoBrSerjXQClT4B2y8fIu5RPc/AVIdo9tjZZYEBWJO1i6nvrP0ufHkLq5KrvPZqpzGHOUqv3V1VVbagFO82Z+1HsMb1rdbrgQOYPMt7b10CVJJ76dxjpxRcMC2/xO0DE8/O696JPlzRkVsJ/mkWFXaWpl1AapfKHIRSEfTNPjZg3Gp9HXcectbKRT2EB/PpkgJu9+AKvxOJcowpPMTwD3etwzcgKp4otzFxL8iHXCN22KQRxPqpc9zwOp0Z5H0f2b9miMlKK3OQy44AwVA+OxleqwOtCz4rKQBrFJopt8GFRZmEWdTcj0bnNWeAqkGh8+D/J6GFckmv1YC6cn0HFEyW8vBY4+MRakle1OI1wUf39b1p2iUbd+PhJHDbGL7qbWuVX9Oj/cJq1ANLXVt4NYXrXqjpw/4ZEj5hypTdVocLYWcotFKV+qBbY5ieGRuhSBkTZxS+9kZU6Pv5VqsRKXzaa7M9uVMLcfwaaWYszh21NK6KeXR3RiLzqCOgivcQHQ+SCFMnQXYfI1zew==
  template:
    metadata:
      name: gotify-admin
      namespace: apps
