---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-default-agent-secret
  namespace: woodpecker
spec:
  encryptedData:
    WOODPECKER_AGENT_SECRET: AgAAr+eoBUVFkV4E5O8zYqQcqGb3hbGFb58fUALBBycx5qPStCB33GaYxSBeLRDgrlGyClieM+P6uKPQ8ZbqEVA9SvKs31yybSxnLBXFiomTomKBy3oeMjpAzrcZK92qfJ4R5fhvDNInjpOpkGwNYqZAh+wayUr28nZSHayhtDw8++2mQxhVLCi9BSGGPlY1ow99wRWDs/oE+fQL7qHSfmhVxuTzzkMwo1daeKGzG5b//vzRY+g18vh8l4YPgSJuWTsE5v0GQQB8adxhvSgARFevfko+Bpl+0glekCZwR7nfaMq9gRAld+MxR94EERQRxRK3f2Yo+kM3cdmCpDyvW+4Xn8CnFIcF1hGj7h7eqNKEMH7ZOYfV/pn7KoRZldkM35z1VmkC14TR40D0plP5tv+tPdfAzb84MmsVk89rHM0vDp/svJ/fJeL360Ft3elDFkS52bCJjGgcN2R5caHnlyJuBZ+9HiU78oeX0HKrCdCTDqk5p5puXlV4Qp+5DvxkEePkk9wvIOaYmRQYVVAft0INfUvXl0//6zcdoh1mGf4NrbEhxxVOpRk5lGAc56fi8RQpY3F2IcqTGz3Gk8SxZO1d7nip6GnfjFhtCTiuVyJm/wPWS+Tf1hxuwmUc1ZRyJ6wJPLB1XzWv02tTB25SCUj+z/z8n5h2WntcVrXmVKXTqj3aHzIUlDQa72Op0tZuRFd9pDZj4mUhDVtHMVA0nqLMZiMT208GmJXTsW5Dg9O3l9m5dwM1MDHj+nDCHmH5t43WOz4KUYVvazKHUU1Y/93x
  template:
    metadata:
      name: woodpecker-default-agent-secret
      namespace: woodpecker
