---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-agent-secret
  namespace: woodpecker
spec:
  encryptedData:
    WOODPECKER_AGENT_SECRET: AgAF8i/JSiCV5T+tBr+EmdIiPv0lF2otxSBZKL0kPV6IzsD6EggDNKt+YUyETvAbGUHmunX6GjCPWRYv13jTKRZAzWhTt8mD1cQnce4zJDji0ubjtfGAWcpUOm+yNRRv7punK7EdWCUxkPNW7D4sgJK/xxXQWFW9Uq9g7CtR0uFIzk1AFcnPMGVLZnJN8cIh4L4R3cqLMzZqbd+sTMwvdwzE2OpOabNsA9EKEvh9l39C431lTjU7E0vv21kbbVCWA4QMDLod9+DUpswZHTx5uJ7mKczVtPahJ9AxLxS1qgQ4TD7t7OZ4gn9Jau+2YqpdRUCuJucrYVX7x51XPME5ZBHzMgOinnmDpCXvfah76UVvhXhjyyo9xTnncwHVAW42JWueJAw/Ba2Znj9Cy11JeweCZ9POLS2ZlG6Pv1Me18AIJxsmvFcqzvFJI2MEeLj/6cqkDhHMI3w3eQkpSKMaAEzpTetiSTVys0XWIF5GHxvm/9N7MuOnFGtesHx8ZiEYEFKhuozWDn0HceFQPTGZ8MYsHOWQxLDg3eQFcVKlySrscdCfQ4QjPqxBNnEbe4W25hJoJghduj87k66i05ZoOCwCyVh/Q0Z6BOR03dspdDITlf27LEqcD3zDkRz7KBQFgZItQYlgfxfpQJT3C7Yue1JE+e+LfG/WaOGsuQ1oaW/YTjtdC20JNB6P0ogvD2sh478Ov5AzTl8/o2TJYmPKNcmCphxdANfBBuZZuosFAuWPqJF11/fNCure+EfXNxC3qcSc+pRp/tnw+MJMp4JYtnrt
  template:
    metadata:
      name: woodpecker-agent-secret
      namespace: woodpecker
