{{- if .Values.outpostIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-authentik-outpost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "200"
    external-dns.alpha.kubernetes.io/ignore: "true"
spec:
  rules:
    - host: {{ .Values.outpostIngress.host | quote }}
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.outpostIngress.host | quote }}
      secretName: {{ .Values.outpostIngress.tlsSecretName | quote }}
{{- end }}
