apiVersion: v2
name: argocd-image-updater
description: ArgoCD Image Updater wrapper chart for m0sh1.cc (DHI)
version: 0.2.5
appVersion: "1.1.1"
type: application
icon: https://argocd-image-updater.readthedocs.io/en/stable/assets/logo.png

dependencies:
  - name: argocd-image-updater-chart
    version: 1.1.1
    repository: oci://dhi.io
    alias: argocd-image-updater
