{{- if .Values.server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scanopy.fullname" . }}-server-data
  labels:
    {{- include "scanopy.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
{{- end }}
