apiVersion: v2
name: qdrant
description: Wrapper chart for Qdrant vector database (RAG for Open WebUI)
type: application
version: 0.1.2
appVersion: "1.14.0"
icon: https://qdrant.tech/img/brand/favicon.svg
sources:
  - https://github.com/qdrant/qdrant
  - https://github.com/qdrant/qdrant-helm
dependencies:
  - name: qdrant
    version: 1.17.0
    repository: https://qdrant.github.io/qdrant-helm
