{{- if .Values.crowdsecBouncer.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
spec:
  plugin:
    crowdsec-bouncer-traefi-plugin:
      enabled: true
      crowdsecLapiScheme: {{ .Values.crowdsecBouncer.lapiScheme }}
      crowdsecLapiHost: {{ .Values.crowdsecBouncer.lapiHost | quote }}
      crowdsecLapiKeyFile: {{ .Values.crowdsecBouncer.lapiKeyFile | quote }}
      crowdsecMode: {{ .Values.crowdsecBouncer.mode }}
      updateIntervalSeconds: {{ .Values.crowdsecBouncer.updateIntervalSeconds }}
      defaultDecisionSeconds: 60
      {{- if .Values.crowdsecBouncer.appsecEnabled }}
      crowdsecAppsecEnabled: true
      crowdsecAppsecHost: {{ .Values.crowdsecBouncer.appsecHost | quote }}
      crowdsecAppsecFailureBlock: {{ .Values.crowdsecBouncer.appsecFailureBlock }}
      crowdsecAppsecUnreachableBlock: {{ .Values.crowdsecBouncer.appsecUnreachableBlock }}
      {{- end }}
      clientTrustedIPs:
      {{- range .Values.crowdsecBouncer.trustedIPs }}
        - {{ . | quote }}
      {{- end }}
{{- end }}
