{{- if .Values.gotenberg.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gotenberg.replicaCount }}
  revisionHistoryLimit: {{ .Values.gotenberg.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.gotenberg.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "gotenberg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gotenberg.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.gotenberg.podSecurityContext | nindent 8 }}
      {{- with .Values.gotenberg.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gotenberg.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gotenberg.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gotenberg
          image: "{{ .Values.gotenberg.image.repository }}:{{ .Values.gotenberg.image.tag }}"
          imagePullPolicy: {{ .Values.gotenberg.image.pullPolicy }}
          {{- with .Values.gotenberg.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.gotenberg.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.gotenberg.service.port }}
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          startupProbe:
            {{- toYaml .Values.gotenberg.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.gotenberg.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.gotenberg.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.gotenberg.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
