{{- if .Values.gotenberg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gotenberg.service.type }}
  ipFamilyPolicy: {{ .Values.gotenberg.service.ipFamilyPolicy | default "SingleStack" }}
  selector:
    {{- include "gotenberg.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gotenberg.service.port }}
      targetPort: http
{{- end }}
