{{- if and .Values.paperlessAi.enabled .Values.paperlessAi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "paperless-ai.fullname" . }}
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.paperlessAi.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.paperlessAi.ingress.className }}
  rules:
    {{- range .Values.paperlessAi.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "paperless-ai.fullname" $ }}
                port:
                  number: {{ $.Values.paperlessAi.service.port }}
          {{- end }}
    {{- end }}
  tls:
    {{- toYaml .Values.paperlessAi.ingress.tls | nindent 4 }}
{{- end }}
