{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-exporter
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
    {{- with .Values.exporter.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "paperless-ngx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: exporter
  endpoints:
    - port: metrics
      interval: {{ .Values.exporter.serviceMonitor.interval | quote }}
{{- end }}
