{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tika.fullname" . }}
  labels:
    {{- include "tika.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tika.replicaCount }}
  revisionHistoryLimit: {{ .Values.tika.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.tika.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "tika.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tika.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.tika.podSecurityContext | nindent 8 }}
      {{- with .Values.tika.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tika.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tika.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tika
          image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}"
          imagePullPolicy: {{ .Values.tika.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.tika.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.tika.service.port }}
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          startupProbe:
            {{- toYaml .Values.tika.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.tika.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.tika.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.tika.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
