apiVersion: v2
name: diode
version: 0.3.19
description: diode wrapper chart
type: application
icon: https://raw.githubusercontent.com/netbox-community/netbox/main/docs/netbox_logo_light.svg
appVersion: "1.5.0"
sources:
- https://github.com/netboxlabs/diode
dependencies:
- name: diode
  version: 1.13.0
  repository: https://netboxlabs.github.io/diode/charts
