apiVersion: v2
name: diode
version: 0.3.16
description: diode wrapper chart
type: application
appVersion: "1.5.0"
sources:
- https://github.com/netboxlabs/diode
dependencies:
- name: diode
  version: 1.13.0
  repository: https://netboxlabs.github.io/diode/charts
