---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    api-key: AgAtapgzFt45vzzE/TAXv64o7ae9SFtAZHuA5NHH7VFIyc96HN6nUYrczS8UX6pT9LplyBhBRVimAdm/uXj8zSLOdJCSEtudYyCtjOaHie8sbdEkmoEFHscq+4/tK6WP1pNnbnxguuPXnnAEBz3Dl8ZqKHTooB9CE0qP+GKP/JaPokO3HNIwh1o2NcQnevxXN06AHbbSiEhIDE3ysuZRPgKe34G0b5INjNZyGC+e+rwAq5QVDHX136ZurFffsW0uf0kEfrN5Yi3JMFrwky8qgj1qK2QS2xM6gvbrvY6EoIitWmqm5ewH4RSjF4k4hjbWAi0Rw448/bZLGTuxou1SfiKe9lBzFwv+gxVB4xJ1gm5JNsz8eyJ1pdHJQAeCbK7IXQmFyW3F9eOKxtwJgmob4amfR+pe8I9FfBK/rpAutdX+lCAuKhluw/Sld7wGLTos9+SkpAJSiHL2Sn7XRsf4d993BFkynJMz5MSQ1jx169m3LkAi38gEsdWCJfdU3wprC/omHEwky7hg+ghGwxWVpnTSOlklgnrCL5zLsXYxL+iyz9qREwg5PkXemuB2wi6N7oT2V5acGuQa/nieiND+G/GMIBgi4bdkF8udL+y5ldKAclOChQfhI4xubLccJMe3GRHvuwm3dtCDBd3j1ZxgXY0yTAsWYdzh3IeRPjNd1IlZCKhFbYssVz7XU8+8FxIpeZRc2Xupco2S63JQZPvsWIFyDZ+SktrIJdTiPbIEy/zXtB8Xtml+acdrnJe+1PRiDlwdfI+XFu/UEqLblRXoM6Nz
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
