---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    api-key: AgAUq7eP3JUVLDB5Qd1IS1Z68JXpnBDgGIZW66X1cWaA2YGK3HNzHwFByzsDwksXnA0K1C0OG8fj3VCKIPOaPknZsPVt56X4a3KYj+QaKH0kRQuTHMz3spx2lXIsF9gp64pCJIbmtCdeNZeejcIyI9UYR5kq/fDDS97H0+pLJNRO4eI4+Pbhgl2QqlEbaaEEpWz0RrQl3X202smxZPc5G7z8QBb+jpxNBzUOStufyFlUffJ3J3Q/mfxIcxY75AGflORxqeTu23nP0WE/4vyLXy0O74Q46bYxzsi+ip0QU3qEDev7kJuDfqqlOnd6o/1ZBNwKyNy9mgAuLow7+GoMe7P3HHkT8dJS/EjHFeu9NQdZNhKfe0SlDkerB1QfLadxKPP/MmwIiH4scfHsytOpt31K8CD0ZqpPVtFNkScuerjrT9DkXJie0F6MxZ95wW4eELLsaIMM6ZyaP/SwNdhGcEEdYU9sJTUUrWAGco8h3fdXjFK66rA92Zx3fwDN/joEhypXXzxjijHT+CFrAdtJoK3cjjdl7GwDDfbjSZNGicYwHNctmZWrka9uNAt6FwFX7Ojc9nr+03QpcjUnAp6CDGXlcT43bblxYG6JU7H+BGNjuEqKZKXhHZa+NOqCNVjI6k21mteMuFdu3oB2IzerwyR8O2KaFWozQAZwswbi5GxeJpv6Z8/zZTSFpS+EBJsGXpA=
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
