---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    api-key: AgBnEHBAmOiKZuM89LyHnViqPOQnQG/afpives9opAhARKMdsAs9Araz17SRZ+Iz4rWiMOy+u8gPsG5gOrlkVwIbAce6oniy/pcj+uMWebFAvKFFx81I/qZZz1cie+y5yUGNu6hhpL+IAbAyr6YjlvO2ZqKZniW0l83OIEBfixjN4SB6SOly2PpFxVMoYuGrKvJ9Z/vn4V1ZJdcuiabNscowpvAxxxJpS60VJ0JKmbvln+DakvnfL87mH2VJxhOB/dsHin0/i5yRgNS8uvdLIC3VPyNdqYhM25Y/Gf753NmV2jR4ZryrM7Ezc0DMGaMTpy1zoJd76wkaZs5q6usQwu/nVFiB8S+9973KIoOuUSEXcRlPkqCuwUHsN6UcItuU77i1YuwqPvWWQ0C8F2piCAuVpN6W16Hj16nXDBaK6GI4eiT/0qMnJOH5AIDRIwtgzAxwgnFIDVr7qTgO/1UiWmvY6DLJYypepMXsIfQqJl9kscjQpeYRPXcqIqYBEtgvje8cHyzUxNMOhlBRcMwNwgYhm98pMc7BZsehC/y0/qx0LrZEPC60jiEnXc0LtSf8EBa3lYgVeMZhIGW57aWgi4Wjzf0kUhRdtksu3SWewJkfMclWTWXJGJUFOyipAY6FkXE2D00KZ7bxORG4xOt9iQ6pzl5XgdZFT9CKbbj1ppgEVo/U+235eOk8FYHxmCjwnNfq9ofvwNvWL7i7zlDCU13MkPGKU3jRXo5ycYzsEQyUXQtFaXuT3XhkDn75
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
