# apps/cluster/external-dns/Chart.yaml
apiVersion: v2
name: external-dns
description: Wrapper chart for external-dns (DHI images) pinned to a vetted release
version: 0.3.3
appVersion: 0.20.0
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
dependencies:
  - name: external-dns-chart
    alias: external-dns
    version: 1.20.0
    repository: oci://dhi.io
