#!/usr/bin/env bash
# Manual Semaphore Runner Registration Script
# This script performs one-time runner registration to obtain unique tokens

set -euo pipefail

REGISTRATION_TOKEN="YdtvkIqi1+GmUcfrzUGKKIJequVXOcSftcqxWhSFSG8="
NAMESPACE="apps"
SERVICE="semaphore"

echo "=== Semaphore Runner Manual Registration ==="
echo ""
echo "Prerequisites:"
echo "  1. Semaphore server must be running: kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=semaphore"
echo "  2. Docker must be installed locally"
echo ""
echo "Step 1: Port-forward to Semaphore server"
echo "  kubectl port-forward -n $NAMESPACE svc/$SERVICE 3000:3000"
echo ""
echo "Step 2: Register runner-01 (run in another terminal)"
echo "  mkdir -p /tmp/semaphore-registration"
echo "  echo '{\"tmp_path\":\"/tmp/semaphore\",\"web_host\":\"http://localhost:3000\"}' > /tmp/semaphore-registration/runner-01.json"
echo "  echo \"$REGISTRATION_TOKEN\" | docker run -i --rm -v /tmp/semaphore-registration/runner-01.json:/config.json semaphoreui/semaphore:v2.16.51 runner register --stdin-registration-token --config /config.json"
echo ""
echo "Step 3: Extract runner-01 token"
echo "  RUNNER_01_TOKEN=\$(jq -r '.runner.token' /tmp/semaphore-registration/runner-01.json)"
echo '  echo "Runner-01 token: $RUNNER_01_TOKEN"'
echo ""
echo "Step 4: Register runner-02"
echo "  echo '{\"tmp_path\":\"/tmp/semaphore\",\"web_host\":\"http://localhost:3000\"}' > /tmp/semaphore-registration/runner-02.json"
echo "  echo \"$REGISTRATION_TOKEN\" | docker run -i --rm -v /tmp/semaphore-registration/runner-02.json:/config.json semaphoreui/semaphore:v2.16.51 runner register --stdin-registration-token --config /config.json"
echo ""
echo "Step 5: Extract runner-02 token"
echo "  RUNNER_02_TOKEN=\$(jq -r '.runner.token' /tmp/semaphore-registration/runner-02.json)"
echo '  echo "Runner-02 token: $RUNNER_02_TOKEN"'
echo ""
echo "Step 6: Update ConfigMaps with real tokens"
echo "  Edit apps/user/semaphore/templates/runner-01-config.yaml"
echo "  Replace 'REPLACE_WITH_REGISTERED_TOKEN' with \$RUNNER_01_TOKEN"
echo ""
echo "  Edit apps/user/semaphore/templates/runner-02-config.yaml"
echo "  Replace 'REPLACE_WITH_REGISTERED_TOKEN' with \$RUNNER_02_TOKEN"
echo ""
echo "Step 7: Enable runners"
echo "  Edit apps/user/semaphore/templates/runner-*-deployment.yaml"
echo "  Change replicas: 0 to replicas: 1"
echo ""
echo "Step 8: Bump chart version and deploy"
echo "  Edit apps/user/semaphore/Chart.yaml - bump version to 0.1.29"
echo "  git add apps/user/semaphore/"
echo "  git commit -m 'feat(semaphore): Add registered runner tokens, enable runners'"
echo "  git push"
echo ""
echo "Step 9: Verify runners connect"
echo "  kubectl get pods -n $NAMESPACE -l app.kubernetes.io/component=runner"
echo "  kubectl logs -n $NAMESPACE -l app.kubernetes.io/component=runner --tail=50"
echo ""
