---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-ghcr
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBYd6yH4cZ32SNY4TO0h++lpKL+/3Bl8EC2rmkK/kxbq9hgyHBTL27zCYImgEBENTRDdBzDHKmbQP8I0zaUwuDjn5Y+3CGlOUQTZiOxLUJ2sRv/uIg2SNZjblK7FlKGN7hiSAJ9fbvuoUYg4PRUz788qBEn2/RgVengDojL2mKFRb1D4Ost63cmwflegZNHJOK73jSI3CGfCH2Nhw7ZI31yFLYKysRCmJrGXQjjqJnGVaObUlfKO+IY67kRrPoquADhlk1U/sffzXQzTxc+FRUBsLfBBvPEyTp+5y6dPI0WXUcifEAGkJhc5tbkb+qG8XqnR1hIF+5IvFrMbUYrDZdb16F8OrLI0guRpE26WHq0gUnaeHLRR5itj4sDyEr/B+yncosp+pIHaXzVxqyoH9P/Knr1zM5zhO8+V10nBwyIpLj/f7J9Jw411JbH/R+QPcH8QmecE4VdsKDcRavilPFDHETtw4NUjuhR1bfGgCBwYOZpWz+RfiUke9f0kOYVLXZh40ZgO78jwZ6TiCHV4uzKCJz1ZleIt7h49z5eu/vOgiltInMOdB6fQ/5LzUPfKoZrwKSZgT1EE0HPBeTrwLGHGUb6izdi5CPQ1+Lowa3mDMolfyYgw6PSqqwumkbKe/TeN/FzLCAZvYcZFzDmO/Q3A60trKbRmXV/KngVLO4nx1lIIYfV2SWIIOKzm0XtVFPR5/mw7lkiLGxA5qtfs5jT+FnGHOZvdmPdln8GIB/IbdCpv+E0lk2uEDTwhZvKx9F29s4FC9Hdjl26dQ9I1lHYIYlrUYg5EFvvzAMXsWoU6MhmwQbuUKhyfNJi82qX04GkatDsHCfy16VJFId5YJSENX2orjR46lTfGj8adW+ufGQqNkP/5JzXO1k49Hl0IvHW1A6BmD9QgXdT6ZV5GNFNTVHjA7ozf1hoRg+j0ZvoDsc=
  template:
    metadata:
      name: argocd-image-updater-ghcr
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
