---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-ghcr
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCFp101ihdiYSb4L/V5LHz7ekhadb63hLo48t0+F1gw7FP1C687Nw79qFTaVLNfXiRPYHd4IztPXyXZOEirmOZGEgeNnOREJZ7Hr+F8k7eVcDINVPf25v4Z0REqh00EkVgYAKyC1aORZKzCs3fkLnmwHf4Do7zwSoTsv2y2C8qJ9djKGF/UDogBGBxIMREyvnUjI0JsnYa4HjUpwVF3KUxkdqWxlwByKIheJYnugq+ouqLSj7t7SsH7cKAxBoCN8T9traPhL+3yKiymqiz/QgG88xvExP1yBtUrXN8ysrnqoJYndsWOAUwNNngB81LSArf8/qnhJ9A5guRT6LUoS+wS50l2jSFfssSqs+PYSI+yC414hqyvOMGRTB6p9ty04qbPJcFQP393qtn0ZhcQZlJCn3z7xOVgpETmauFiJgZGZBZa5tnP/rDk9MFgWzjLiOx2p5YmAtcBCv1DanOniJVbFcGs2e1rTF74uYg+igc45dYGE89Qwi60C24CicfE7gCzV0TQ9LHiDckDXnLA4Ys1qCPGVCbJgWMBZONTt3PPkznMtyIukZGLphbywBqcVtev6Q426Ebep/H2Ssg3BD/LRn/NHLywiWc240s9XYCZRiaudRB0hHFXr7utgSNAZvFL3b/HX91jPgAEQPemGmhHsoxZqR1yNWzU7F/pXC/Sm/IqLz99ziULzIwZBa3Uhd26Yar9fBJT9yIdMKeXWqUa+MYGuJed7wZ027E3UC50a3jwE5taoSBmnR2DG9zEDvyTxJxqR13v0Xxof0iBENsEo3Z4Gs6Bkom4B/ne4NHtD5VMjwarxzgAych/UX/CgXkUrgUsTav4Y0CBehClpf4BiNcquamSBztyrnUQPH6VaaSO5pjMxc/4WeON6N9ocqUH7spfz1x6E4sGigRSpyAkWqKqgIkRtSug80qlHTHdiRw=
  template:
    metadata:
      name: argocd-image-updater-ghcr
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
