{{- range $set := .Values.policySets }}
{{- if and $set.enabled ($set.defaults.allowDnsEgress | default false) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cluster-network-policies.policyName" (dict "namespace" $set.namespace "suffix" "allow-dns-egress") }}
  namespace: {{ $set.namespace }}
  labels:
{{ include "cluster-network-policies.commonLabels" $ | indent 4 }}
{{- with $set.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $.Values.global.kubeSystemNamespace | quote }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
{{- end }}
{{- end }}
