---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-pdf-auth
  namespace: apps
spec:
  encryptedData:
    SECURITY_INITIALLOGIN_PASSWORD: AgCmzkWkMQc4syn/xuLnFefJ1hdOLzrVgC66s0ggU7eRLmChlHl5InlDvU5HoG3eWSJdjE8g2mkcSFOd3HuNQfHjSw63sq8uA9H7rf5r1lkAArhtlGu4VjQRjawwddclEV+2wiqanwqCUbdUMJJ5a0uGqwqvgrV+4r0vtcuhuayvAVXYbkDerdgSSg/1R00HZ/NndDm3rBXXunmXCX/m1MqWwAfGK/SOk3FYLJf7gTFRgnXiv+MRSnG37D3aH+gWd+ER75HIpKDww7dvKxXuUjSG7uFT9P8hlnpPxqfs+UBCTVQgWlklWZfBTn6wQrROEyAd+2vUpMyvmEJWPEZ92ap3mc5HPWWeJTyc3k5QNRJsbM1FhMQj9TL+RwqQUIUoCdi5zbhDoKnjBrxFrvcPd4VjKfZ6BjZ5M0hrh5VTQnV3Xtm3KKM/O5sX0UNHlv+inyGq1vupev8tmSnmtsKp/4QNJu02P2X++3rAC88BzQcYVcTzPdHuk8amIwzMYv56PO7XP11hzdsp6H2yAUcvCYRUdC1BTke6jd7LRyW55/p1H9D5cf6pMpY4OFDo5vtIXa3q/rOX1uqHv/qSZ5vFaqQGFY5XQSZ/pofU175lyLmzBF1U51h5DhoZrDEEL4AjA7HUMorV34ofgJypSWG0jRH1aje6toi7lYmEKFSVBaE5zu4xOrJMWWtJ3wmPZpIHAf6fRNI1Blxh4eoZ9HXayD3LbMlGrOBacpSq2GnJhfEQGA==
    SECURITY_INITIALLOGIN_USERNAME: AgBtbX1FdBKBSfCtpDVLswOGRyYiw6JfOsgRwC/yHEjdrogVXcfQe4KxfcaHI8WuYnaSkIqBHl/tyJPESdTH4vtV4NPFRDN3u1CsYMNh8N23rKCGlJIwqWFjnK4X+qeeSoALe/pPSSFjm64X7F2WJygUyGKsr/Tncw0P5uJ6F6B3SSXkm1+njtSmpEpblrw/SWIFrtFn9Fw6FkZlJuBPPm3QgizXX/KIhRggUi4hdXWTQ5PvhzFHChWMQ2XCbbU5jUtDX/YESkg5vQteyFZWCwkhEfRe0/2VVekfMAbgCnJT80OdJIzDB7WhGP4Z9ArzJhYKZvloKb2afRtfxpx6GxWF+KT5JfhPnwJwniNozec4rpKmBC7IpQBTZ1QzfI1J/RkugTu2SZR6Vd6/B73FrtSxmSM/499trnBTz2mAy9yBb9n6Nk82SV38e9rN23fOlwyHjHy5BBNur46zb9/CVqXNrg5vNJTrHuqvZDHK2OSd1SMhQHmwWcalTAKVQcuWkfBp3FGuOt6MyIpL9U/QtNb0WIXwoQpXBRdr4Rr0VuIf17sbirQ3iiwG0IyAPCt1gAMwQ1rzKbkFfaRN7WqgdL2zaFFa6owECLfEqNGoQEyXUel3gWyp/BBdZgWFal5VYa4m96j+cp+/KBrZkwbNe3ikZLbO+wKL/ptWroRJhPrBpmuTa0XSfopWwf5QPlrXIDop6165Ig==
  template:
    metadata:
      name: stirling-pdf-auth
      namespace: apps
