apiVersion: v2
name: uptime-kuma
version: 0.6.0
description: uptime-kuma wrapper chart
type: application
appVersion: "2.1.1"
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
sources:
  - https://github.com/louislam/uptime-kuma
dependencies:
  - name: uptime-kuma
    version: 4.0.0
    repository: https://dirsigler.github.io/uptime-kuma-helm
