apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argocd
spec:
  description: Root app-of-apps project for ArgoCD application manifests
  sourceRepos:
    - https://github.com/sm-moshi/infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
