apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
  namespace: argocd
spec:
  description: Platform and cluster infrastructure applications
  sourceRepos:
    - https://github.com/sm-moshi/infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: apps
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: cloudflared
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
    - server: https://kubernetes.default.svc
      namespace: crowdsec
    - server: https://kubernetes.default.svc
      namespace: csi-proxmox
    - server: https://kubernetes.default.svc
      namespace: external-dns
    - server: https://kubernetes.default.svc
      namespace: garage
    - server: https://kubernetes.default.svc
      namespace: garage-system
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: kured
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: origin-ca-issuer
    - server: https://kubernetes.default.svc
      namespace: reflector
    - server: https://kubernetes.default.svc
      namespace: renovate-operator
    - server: https://kubernetes.default.svc
      namespace: sealed-secrets
    - server: https://kubernetes.default.svc
      namespace: traefik
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
