---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: termix-opkssh
  namespace: apps
spec:
  encryptedData:
    client_id: AgCKmFPVBUpUxtIg4NNAa9hShWmo4ADDqf0URNx6W/HqozjepguU5py6ZK3nJ7QFJ9N/5/qvoWn32JCkem6v8rRoCEFnHKPhqzm3932CWv7Pip0zOpiPDR7YAvQPXrB9bvPHpCa111M/fGlJ/Tf69afptQvpTIgT+d6cn8TIvxpuhfbdIe8eljYwJexB7uZ6DWWAdI3i3e9CMbkVgcrYqTFyl/GPCCOCl1tDJfEOxFtWlWp03c8M8XxqJHHEmOLtCU4ZuzIcQW40x0sCyZD5FyBFf0TQIAkxPZ8Kj19t8J6CFCZkFOLwRzhFsttL+kzbEQnL6eJcpQvOoH9nQkmU9ubXhf5AFdLW2slovTfaggrTCkvgkNXYpckAQXFxe2eJS6aVXU7pMyWJ/1V5JiJ3/1agyo4BkpNjjm0HG6BBclhxBc2R9FJOd1hAqn9HRhGKZ4Ty2WNUuuadYWAKeNDU2lG+f9kMKysDlCrGrG813sP1wE1ym5iFOHuVtML1sEPyuco8pTX8J7Ffu/113fh8y6IHFhLZIkGLZjVNYOWTjUGAFyFJPnxngwoUADCQU91D2OBh+t+pdnTRs3WAaYSnRihq49ALmOxYXhhwxJwcA1BMZx7Fb574dDUWI2c/u2jMwL+qTqylANMZCzal6VJwZwLjBdtuYxKpeLneZQhaPo+hqZ/xMLMCSFIihlg/ic0xgibo11F6KgLfg+8/Taim+e+Bqky76LoM2cD7hZ/jYhEP9A==
    client_secret: AgBkoY7HG/InCChb+z1P1YVmmC8mzc9Hdf+poQ/a5xFsUh2NoqKYuUP/YC7uVL3sDTE1MYqibD6pF1GRm6w1FzBdpEFxr1TO+mDnry1HCYth8qrZVngUTdcrbUIGfSWLS6jIbieecfv5cQOQORNdZj9QT4qdvIEEECN7v9DrN/2ysZuwG9FSMEezoERQDZN4KkX0uQHdTtgYMGr81iuRnib0n/b1Rawyzj9slC/0hzNvNXVHZj6wIhxWSLwLYI9i0yX8Wboah8MTYpgyYf4OWLdVFYC41E5CWPQXrcCFP/j6TwSlQU/ifJUaLKLebSwYwcpiWohvJPJwEfQXVm+i5IOgXGdrQToO2IhYtwHMsNRSgy9TP2zru7l2zz8Z6p9Kg32pC1E5rRPn3yONl8pv5QjKprsQ5W6ZNi7YfOoEpLkcgvl5xLGVHC1jk6wAO3i4N79axKoPTOD8iUi7dLZabRgNO1G0DxiwExLUDOfxAkgtvpUlkQfc2ALA0O6OcckiM7Vrcdq+If9JXFv9mrMt+jWuCSZc2CMhOtWxqf/vGWaZWJaLY/LXpVx5U2QINQkZw1dIRgYsPwn2d3/Xyludg6rhZRPWMtqafz7jCGGsi7/Og5/KsM5UsXvZW2VVd+LrHjiexdijlqRtyc49lnduNiumxphVIoW8wUy0ra1UnvRpsug1HZLei0c1IJT+jRYUkddmhw60Dk+bUR3TS+VeUYya2gPZEjuGBb/hGAXWkYbV2Sd4JFw10epiDYPejC5B6tA9/BDl95uUy0YevuV3DzRa
  template:
    metadata:
      name: termix-opkssh
      namespace: apps
