---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: termix-oidc
  namespace: apps
spec:
  encryptedData:
    client_id: AgB4T2BlruU+dHHnoyIHWw3YI6gjy6rLx0vZ/rN56TU8UkSCOWNuwNGVJNzyaow8+ImidgroFuW83hncbxzEzc3fSNDRlWNHwOluW1WFh+mGiSdRYv9Ob/wtoQ66dlpc6Pg/xLLrFAF5Z2iuH4wmSx+0qRJW9zTNDVrXdCj3/bdwcFvt2P6dldCnqIgSinja0tZclDSGMAPto+0oQbl+P4FiYY90jFS9en6gjjS3fYdgW4hCRHoTryl46x1n6xhtvQzhkXaJENVyJRm/u4iKvyX3wWbGRkUgNvS2iQZy6STdD/ouy9XnD1Mq6RYblMP/ugeuh3o5Q6djhVDqMb8zGXAfEzvQMh46x/8Rgae3LdYbcndJMiUUL0br4Jma/hMAWlUaNzysm7mGFGkJ6GqJDQiIQw5n+BVkmfY9XTJtZjxOT5zhT2yMytvlN4vSHdXX8l7pw1uDnam5a+G93tZZr613p+r3Zv+KeZEzcXt8KaL+QACr53EqWCVd53rMW0A8D3RtOijo5fscSnLevAWLXn80t/e1Z1qusnvdquWY5Fu8Tbg72r97l1gsds9nH6/A/BDu/SqBRhlBvE87/1wdgsxCQ6ntO89wjfUKXXqJ11//xlszRI7Rtl0hWrkhA/3NmZbRK1Ziym/sIw1J4SkPcaxmXeD74hds/2OdLMyF8NjTT88QZGcl3gqFWHFCtTpwiJBAUC3tQ7MJVojaLMdvA+cGdbmx3aRGwFHxmSaXfO3zWuZXgUwpVZXS
    client_secret: AgATpzMDUCB99ELinzeZa5uValqOvBTKMSviaXhyTd0rnCC8NDolfS0EcR6MtGouoJFvgIzH9ss3Tj8zeBRWjzJ7mWPcR9c2aTZUGYy+GqgDzfEvXsSJmIRFioSRsU2s/TfYTp1dfw6Zpi4sloTl8w89m7wX7K/UG3FaS7/4tBHSfCLkEZ+RFtgjix/E8KUb9uw24OLdbg53vfgmeTHCoXg8sNeiv8uQqQxCFrfNigvRXgUWCrr2oasrLoL87wel1VCvEC4PogzzVJ/1Ebd/NNrCkGX0AwPGglOkwLvGuPQiDP3EU9WOtPgWZQtoq5mI6ygi4wKQm6jvZfc7Jts8KfPzkaf/kZ4c0wMB4KKdub4usoDBuOlGuDtp1NFFUL3zJX9DJ0WezlJ37fFLXAQ2KaGBLtJlb7HytCQcCAmm8MZMbzDElBnzHLKIBI/wqGXYFLPo1grWHdbk0WGyNa/adhuQci1A5ADGY1moF49XmWR4sjNkq4xBo6PNZCPxilmqqQdftpENPlD8jVEdYwTVxyLlUOCJ6jKzI/mOatv9aA3emso3Fy9OfBaN651AsnzUQTzO2+zxakjFpDXiOBchqW3ZcI0E9Wt91tgeSWVPFfba/dFVNqm52CivsTtCPKdoJpTmzGwJhIxQBWQ70Vs81gjsqyWPLezyvO2BOQ43nM4uazxRE9pgSv2qYy/aiGOsZzQ3SFnJHh/Qv5L70yFYbU2azW9MXdZoY/4qFtZtLOB0OrdzQ/Ut3DvR5YxMHilifZJqcw5QDzQjNFMIg12OzQ9a
  template:
    metadata:
      name: termix-oidc
      namespace: apps
